/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.LocalAgent;

import Business.LocalAgent.LocalAgent;
import Business.Payment.Payment;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author JJPL
 */
public class LocalAgentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LocalAgentWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Person person;
    LocalAgent localAgent;
    public LocalAgentWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        
        newRequestsJtable.setVisible(false);
        this.person = userAccount.getPerson();
        if(person instanceof LocalAgent)
            localAgent = (LocalAgent)person;
        welcomeJlbl.setText("Welcome "+userAccount.getUsername()+",");
        populateAccountSummary();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void populateAccountSummary()
    {
       accountNoJtext1.setText(String.valueOf(localAgent.getSavingsAccount().getAccountNumber()));
       availableBalanceJtext.setText(String.valueOf(localAgent.getSavingsAccount().getAccountBalance()));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        enterpriseNameJlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        accountSummaryJPanel = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        availableBalanceJtext = new javax.swing.JTextField();
        accountNoJtext1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        manageProfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newRequestsJtable = new javax.swing.JTable(){

        };

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(51, 255, 51));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayeredPane1.setOpaque(true);

        enterpriseNameJlbl.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        enterpriseNameJlbl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseNameJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(788, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(enterpriseNameJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(enterpriseNameJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Check new transfer requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 220, 30));

        accountSummaryJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accountSummaryJPanel.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 940, 10);

        jLabel6.setText("AVAILABLE BALANCE:");
        accountSummaryJPanel.add(jLabel6);
        jLabel6.setBounds(90, 100, 240, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("ACCOUNT SUMMARY:");
        accountSummaryJPanel.add(jLabel8);
        jLabel8.setBounds(10, 10, 130, 20);

        availableBalanceJtext.setEnabled(false);
        accountSummaryJPanel.add(availableBalanceJtext);
        availableBalanceJtext.setBounds(330, 90, 170, 30);

        accountNoJtext1.setEnabled(false);
        accountSummaryJPanel.add(accountNoJtext1);
        accountNoJtext1.setBounds(330, 50, 330, 30);

        jLabel4.setText("ACCOUNT NO:");
        accountSummaryJPanel.add(jLabel4);
        jLabel4.setBounds(90, 60, 240, 20);

        add(accountSummaryJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 850, 140));

        welcomeJlbl.setText("ACCOUNT NO:");
        add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 20));

        manageProfile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        manageProfile.setText("Manage Profile");
        add(manageProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        newRequestsJtable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newRequestsJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Number", "Donation Amount", "Recipient"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        newRequestsJtable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        newRequestsJtable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(newRequestsJtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 850, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        newRequestsJtable.setVisible(true);
        populateRequestsTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void populateRequestsTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)newRequestsJtable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest workRequest:userAccount.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof Payment)
            {
                Payment payment = (Payment)workRequest;
               Object row[]= new Object[3];
               row[0]=payment.getRequestId();
               row[1]=payment.getAmount();
               row[2]=payment.getPaymentRecipientList().get(0);
               dtm.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoJtext1;
    private javax.swing.JLayeredPane accountSummaryJPanel;
    private javax.swing.JTextField availableBalanceJtext;
    private javax.swing.JLabel enterpriseNameJlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton manageProfile;
    private javax.swing.JTable newRequestsJtable;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
