/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Recipient;

import Business.Recipient.Recipient;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class CheckAccountBalanceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckAccountBalanceJPanel
     */
    private JPanel userProcessContainer;
    private Recipient recipient;
    public CheckAccountBalanceJPanel(JPanel userProcessContainer,Recipient recipient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.recipient = recipient;
        
        populateAccountSummary();
    }
    
    public void populateAccountSummary()
    {
        availableBalanceJtext.setText(String.valueOf(recipient.getMobileAccount().getAccountBalance()));
        registeredDateJtext.setText(String.valueOf(recipient.getRegisteredDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        availableBalanceJtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        registeredDateJtext = new javax.swing.JTextField();
        backJbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayJPanel.setOpaque(true);
        displayJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBackground(new java.awt.Color(102, 204, 255));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERADICATE POVERTY");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 26));

        jLabel2.setText("Share Happiness");
        jLayeredPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        displayJPanel.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 54));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ACCOUNT SUMMARY");

        jLabel4.setText("Available Balance:");

        availableBalanceJtext.setEnabled(false);

        jLabel5.setText("Registered Date:");

        registeredDateJtext.setEnabled(false);

        backJbutton.setText("OK");
        backJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registeredDateJtext)
                            .addComponent(availableBalanceJtext)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(backJbutton)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(availableBalanceJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registeredDateJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(backJbutton)
                .addGap(23, 23, 23))
        );
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(availableBalanceJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registeredDateJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(backJbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        displayJPanel.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 270, 220));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("***Please do not share your MPIN with anyone");
        displayJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, -1));

        welcomeJlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        welcomeJlbl.setText("jLabel4");
        displayJPanel.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, -1));

        add(displayJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 340, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void backJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbuttonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availableBalanceJtext;
    private javax.swing.JButton backJbutton;
    private javax.swing.JLayeredPane displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JTextField registeredDateJtext;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
