/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Recipient;

import Business.Person.Person;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class ConfigureProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConfigureProfileJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Recipient recipient;
    private Person person;
    
    public ConfigureProfileJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
    
        this.person = userAccount.getPerson();
        if(person instanceof Recipient)
            recipient = (Recipient)person;
        
        welcomeJlbl.setText("Welcome "+userAccount.getUsername());
        passwordValidatorJlbl.setText("");
        passwordStrengthJlbl.setText("");
        passwordStrengthValueJlbl.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        backJbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        answer1Jtext = new javax.swing.JTextField();
        question1ComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        question2ComboBox = new javax.swing.JComboBox();
        answer2Jtext = new javax.swing.JTextField();
        startKeyComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        submitAnswersJbutton = new javax.swing.JButton();
        oldMpinJtext = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newMpinJtext = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        passwordValidatorJlbl = new javax.swing.JLabel();
        passwordStrengthJlbl = new javax.swing.JLabel();
        passwordStrengthValueJlbl = new javax.swing.JLabel();
        resetMpinJtext = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayJPanel.setOpaque(true);
        displayJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBackground(new java.awt.Color(102, 204, 255));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERADICATE POVERTY");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 26));

        jLabel2.setText("Share Happiness");
        jLayeredPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        displayJPanel.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 54));

        welcomeJlbl.setText("jLabel4");
        displayJPanel.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, -1));

        backJbutton.setText("<<BACK");
        backJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbuttonActionPerformed(evt);
            }
        });
        displayJPanel.add(backJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("***Please do not share your MPIN with anyone");
        displayJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 280, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Start key:");
        displayJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, -1));

        answer1Jtext.setForeground(new java.awt.Color(204, 204, 204));
        answer1Jtext.setText("Answer:");
        answer1Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answer1JtextFocusGained(evt);
            }
        });
        displayJPanel.add(answer1Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 30));

        question1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name of my childhood friend?", "Name of my favourite movie?", "Name of my first school teacher?" }));
        displayJPanel.add(question1ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 30));

        jLabel8.setText("1)");
        displayJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel9.setText("1)");
        displayJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        question2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amount of my first salary?", "My favourite colour?", "Name of my first girlfriend/boyfriend?", " " }));
        displayJPanel.add(question2ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 30));

        answer2Jtext.setForeground(new java.awt.Color(204, 204, 204));
        answer2Jtext.setText("Answer:");
        answer2Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answer2JtextFocusGained(evt);
            }
        });
        answer2Jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2JtextActionPerformed(evt);
            }
        });
        displayJPanel.add(answer2Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, 30));

        startKeyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date of Birth", "Spouse Name", "Unique Id no" }));
        displayJPanel.add(startKeyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 180, -1));
        displayJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Security Questions:");
        displayJPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, -1));

        jLabel12.setText("Field for start key:");
        displayJPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 100, -1));

        submitAnswersJbutton.setText("Submit Answers");
        submitAnswersJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswersJbuttonActionPerformed(evt);
            }
        });
        displayJPanel.add(submitAnswersJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 170, -1));
        displayJPanel.add(oldMpinJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, 30));

        jLabel3.setText("Old MPIN:");
        displayJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel4.setText("New MPIN:");
        displayJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        newMpinJtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newMpinJtextKeyPressed(evt);
            }
        });
        displayJPanel.add(newMpinJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Change MPIN:");
        displayJPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        passwordValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        passwordValidatorJlbl.setText("jLabel14");
        displayJPanel.add(passwordValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, -1));

        passwordStrengthJlbl.setText("jLabel6");
        displayJPanel.add(passwordStrengthJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, -1));

        passwordStrengthValueJlbl.setText("jLabel6");
        displayJPanel.add(passwordStrengthValueJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        resetMpinJtext.setText("RESET MPIN");
        resetMpinJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMpinJtextActionPerformed(evt);
            }
        });
        displayJPanel.add(resetMpinJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, -1));

        add(displayJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 340, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void backJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJbuttonActionPerformed

    private void answer2JtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2JtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2JtextActionPerformed

    private void newMpinJtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newMpinJtextKeyPressed
        // TODO add your handling code here:
        
        passwordStrengthJlbl.setText("Password Strength:");
        String pattern = "(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{5,10}";
       boolean flag = String.valueOf(newMpinJtext.getPassword()).trim().matches(pattern);
       if(flag)
       {
        passwordStrengthValueJlbl.setText("Good");
        passwordStrengthValueJlbl.setForeground(Color.green);
       }
       
       else
       {
       passwordStrengthValueJlbl.setText("Bad");
        passwordStrengthValueJlbl.setForeground(Color.red);    
       }
           
       
    }//GEN-LAST:event_newMpinJtextKeyPressed

    private void resetMpinJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMpinJtextActionPerformed
        // TODO add your handling code here:
        boolean errorFlag=false;
        passwordValidatorJlbl.setText("");
        passwordStrengthJlbl.setText("");
        passwordStrengthValueJlbl.setText("");
        if(!Validation.validateTextFieldForPassword(newMpinJtext))
        {
            passwordValidatorJlbl.setText("Please enter valid password");
            errorFlag=true;
        }
        
        else if(!String.valueOf(oldMpinJtext.getPassword()).equalsIgnoreCase(recipient.getMpin()))
        {
            passwordValidatorJlbl.setText("Incorrect old MPIN");
            errorFlag=true;
        }
        
        if(!errorFlag)
        {
            int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to change MPIN","Please confirm",JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
            recipient.setMpin(String.valueOf(newMpinJtext.getPassword()));
            JOptionPane.showMessageDialog(null,"MPIN updated successfully","MPIN updated",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
       
       
 
        
        
    }//GEN-LAST:event_resetMpinJtextActionPerformed

    private void submitAnswersJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswersJbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        String errorMsg = "";
        if(!Validation.validateTextFieldsForNonEmpty(answer1Jtext)||answer1Jtext.getText().trim().equalsIgnoreCase("Answer:"))
        {
            errorFlag=true;
            errorMsg = "Please enter answer for question1";
            
        }
        
        
        if(!Validation.validateTextFieldsForNonEmpty(answer2Jtext)||answer2Jtext.getText().trim().equalsIgnoreCase("Answer:"))
        {
            errorFlag=true;
            errorMsg+= "\n Please enter answer for question2";
            
        }
        
        if(!errorFlag)
        {
            recipient.getProfile().setQuestion1(String.valueOf(question1ComboBox.getSelectedItem()));
            recipient.getProfile().setQuestion2(String.valueOf(question2ComboBox.getSelectedItem()));
            recipient.getProfile().setAnswer1(answer1Jtext.getText().trim());
            recipient.getProfile().setAnswer2(answer2Jtext.getText().trim());
            
            if(String.valueOf(startKeyComboBox.getSelectedItem()).equalsIgnoreCase("Date of birth"))
            {
                recipient.setStartKey(String.valueOf(recipient.getDateOfBirth()));
                
            }
            
            
            else if(String.valueOf(startKeyComboBox.getSelectedItem()).equalsIgnoreCase("Name of spouse"))
            {
                recipient.setStartKey(String.valueOf(recipient.getProfile().getSpouseName()));
                
            }
            
            else if(String.valueOf(startKeyComboBox.getSelectedItem()).equalsIgnoreCase("Unique id"))
            {
                recipient.setStartKey(String.valueOf(recipient.getUniqueId()));
                
            }
            
            
            JOptionPane.showMessageDialog(null,"Profile details updated successfully","Details updated",JOptionPane.INFORMATION_MESSAGE);
                    
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,errorMsg,"Invalid input",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_submitAnswersJbuttonActionPerformed

    private void answer1JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answer1JtextFocusGained
        // TODO add your handling code here:
        answer1Jtext.setText("");
        answer1Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_answer1JtextFocusGained

    private void answer2JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answer2JtextFocusGained
        // TODO add your handling code here:
        
        answer2Jtext.setText("");
        answer2Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_answer2JtextFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1Jtext;
    private javax.swing.JTextField answer2Jtext;
    private javax.swing.JButton backJbutton;
    private javax.swing.JLayeredPane displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField newMpinJtext;
    private javax.swing.JPasswordField oldMpinJtext;
    private javax.swing.JLabel passwordStrengthJlbl;
    private javax.swing.JLabel passwordStrengthValueJlbl;
    private javax.swing.JLabel passwordValidatorJlbl;
    private javax.swing.JComboBox question1ComboBox;
    private javax.swing.JComboBox question2ComboBox;
    private javax.swing.JButton resetMpinJtext;
    private javax.swing.JComboBox startKeyComboBox;
    private javax.swing.JButton submitAnswersJbutton;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
