/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Recipient;

import Business.Person.Person;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class ForgotPasswordJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ForgotPasswordJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Recipient recipient;
    private Person person;
    
    public ForgotPasswordJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
        this.person = userAccount.getPerson();
        if(person instanceof Recipient)
            this.recipient = (Recipient)person;
        populateQuestions();
    }
    
    public void populateQuestions()
    {
        question1Jlbl.setText("1)"+recipient.getProfile().getQuestion1());
        question2Jlbl.setText("2)"+recipient.getProfile().getQuestion2());
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        backJbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        question1Jlbl = new javax.swing.JLabel();
        answer1Jtext = new javax.swing.JTextField();
        question2Jlbl = new javax.swing.JLabel();
        answer2Jtext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        submitJbutton = new javax.swing.JButton();
        startKeyJtext = new javax.swing.JPasswordField();

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayJPanel.setOpaque(true);
        displayJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBackground(new java.awt.Color(102, 204, 255));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERADICATE POVERTY");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 26));

        jLabel2.setText("Share Happiness");
        jLayeredPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        displayJPanel.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 54));

        welcomeJlbl.setText("jLabel4");
        displayJPanel.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, -1));

        backJbutton.setText("<<BACK");
        backJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbuttonActionPerformed(evt);
            }
        });
        displayJPanel.add(backJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("*** Contact 800 800 800 in case of any MPIN reset issues");
        displayJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Start key:");
        displayJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, -1));

        question1Jlbl.setText("jLabel3");
        displayJPanel.add(question1Jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 300, -1));

        answer1Jtext.setForeground(new java.awt.Color(204, 204, 204));
        answer1Jtext.setText("Answer:");
        answer1Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answer1JtextFocusGained(evt);
            }
        });
        displayJPanel.add(answer1Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 30));

        question2Jlbl.setText("jLabel3");
        displayJPanel.add(question2Jlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 300, -1));

        answer2Jtext.setForeground(new java.awt.Color(204, 204, 204));
        answer2Jtext.setText("Answer:");
        answer2Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                answer2JtextFocusGained(evt);
            }
        });
        displayJPanel.add(answer2Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 300, 30));
        displayJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 272, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Security Questions:");
        displayJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        submitJbutton.setText("SUBMIT");
        submitJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbuttonActionPerformed(evt);
            }
        });
        displayJPanel.add(submitJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 30));
        displayJPanel.add(startKeyJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJbuttonActionPerformed

    private void answer1JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answer1JtextFocusGained
        // TODO add your handling code here:
        
        answer1Jtext.setText("");
        answer1Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_answer1JtextFocusGained

    private void submitJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        String errorMsg="";
        if(!Validation.validateTextFieldsForNonEmpty(answer1Jtext)||answer1Jtext.getText().trim().equalsIgnoreCase("Answer:"))
        {
            errorFlag=true;
            errorMsg = "Please enter answer for question1";
            
        }
        
        
        if(!Validation.validateTextFieldsForNonEmpty(answer2Jtext)||answer2Jtext.getText().trim().equalsIgnoreCase("Answer:"))
        {
            errorFlag=true;
            errorMsg+= "\n Please enter answer for question2";
            
        }
        
        if(!Validation.validateTextFieldsForNonEmpty(startKeyJtext))
        {
            errorFlag=true;
            errorMsg+="Please enter start key";
        }
        
        if(!errorFlag)
        {
            if(String.valueOf(startKeyJtext.getPassword()).equals(recipient.getStartKey()))
            {
                JOptionPane.showMessageDialog(null,"Your MPIN is "+recipient.getMpin()+"\n Please do not share it with anyone.");
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid or incorrect start key","Authentication Failed",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_submitJbuttonActionPerformed

    private void answer2JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answer2JtextFocusGained
        // TODO add your handling code here:
        
        answer2Jtext.setText("");
        answer2Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_answer2JtextFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer1Jtext;
    private javax.swing.JTextField answer2Jtext;
    private javax.swing.JButton backJbutton;
    private javax.swing.JLayeredPane displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel question1Jlbl;
    private javax.swing.JLabel question2Jlbl;
    private javax.swing.JPasswordField startKeyJtext;
    private javax.swing.JButton submitJbutton;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
