/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Recipient;

import Business.Person.Person;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class RecipientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecipientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Person person;
    private Recipient recipient;
    public RecipientWorkAreaJPanel(JPanel upc,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=upc;
        this.userAccount = userAccount;
        hideJPanels();
        welcomeJlbl.setText("Welcome "+userAccount.getUsername()+", ");
        person = userAccount.getPerson();
        if(person instanceof Recipient)
            recipient = (Recipient)person;
    }
    
    public void hideJPanels()
    {
        enterPinJPanel.setVisible(false);
    }
    
    public boolean validateForm()
    {
        boolean errorFlag=false;
        
        if(!Validation.validateTextFieldForCCV(mpinJtext))
        {
            mpinValidatorJlbl.setText("Please enter valid pin");
            errorFlag=true;
        }
        
        
        
        return errorFlag;
    }
    
    
    public boolean authenticateUser(String password)
    {
        boolean validUser=true;
        int counter=0;
        if(counter==5)
        {
        validUser=false;    
        userAccount.setIsActive(false);
        }
        
        else if(!recipient.getMpin().equalsIgnoreCase(password))
        {
            validUser=false;
            mpinValidatorJlbl.setText("Incorrect pin.");
            mpinValidatorJlbl2.setText("Account will be locked after 5 attempts");
            counter++;
        }
        
        return validUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane4 = new javax.swing.JDesktopPane();
        popupMenu1 = new java.awt.PopupMenu();
        displayJPanel = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuJlist = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        enterPinJPanel = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        goJbutton = new javax.swing.JButton();
        mpinValidatorJlbl = new javax.swing.JLabel();
        mpinJtext = new javax.swing.JPasswordField();
        mpinValidatorJlbl2 = new javax.swing.JLabel();
        goJbutton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        keypadJPanel = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jDesktopPane8 = new javax.swing.JDesktopPane();

        jDesktopPane4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayJPanel.setOpaque(true);
        displayJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBackground(new java.awt.Color(102, 204, 255));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERADICATE POVERTY");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 26));

        jLabel2.setText("Share Happiness");
        jLayeredPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, -1));

        displayJPanel.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 330, 50));

        menuJlist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuJlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Inbox", "Check Account Balance", "Withdraw Money", "Forgot MPIN" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuJlist.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuJlistFocusGained(evt);
            }
        });
        menuJlist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                menuJlistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(menuJlist);

        displayJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 295, 100));

        jLabel3.setText("Please choose any one option and click on Go>>:");
        displayJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        welcomeJlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        welcomeJlbl.setText("jLabel4");
        displayJPanel.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 260, -1));

        enterPinJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Please enter your MPIN to continue:");

        goJbutton.setText(">>");
        goJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJbuttonActionPerformed(evt);
            }
        });

        mpinValidatorJlbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mpinValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));

        mpinValidatorJlbl2.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout enterPinJPanelLayout = new javax.swing.GroupLayout(enterPinJPanel);
        enterPinJPanel.setLayout(enterPinJPanelLayout);
        enterPinJPanelLayout.setHorizontalGroup(
            enterPinJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPinJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(enterPinJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(enterPinJPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(mpinJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(goJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(enterPinJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(enterPinJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpinValidatorJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mpinValidatorJlbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        enterPinJPanelLayout.setVerticalGroup(
            enterPinJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPinJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enterPinJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mpinJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpinValidatorJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpinValidatorJlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        enterPinJPanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterPinJPanel.setLayer(goJbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterPinJPanel.setLayer(mpinValidatorJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterPinJPanel.setLayer(mpinJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        enterPinJPanel.setLayer(mpinValidatorJlbl2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        displayJPanel.add(enterPinJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 120));

        goJbutton1.setText("GO>>>");
        goJbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJbutton1ActionPerformed(evt);
            }
        });
        displayJPanel.add(goJbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("***Please do not share your MPIN with anyone");
        displayJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 280, -1));

        jButton1.setText("CONFIGURE PROFILE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        displayJPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 60, 140, -1));

        add(displayJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 330, 440));

        keypadJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout keypadJPanelLayout = new javax.swing.GroupLayout(keypadJPanel);
        keypadJPanel.setLayout(keypadJPanelLayout);
        keypadJPanelLayout.setHorizontalGroup(
            keypadJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        keypadJPanelLayout.setVerticalGroup(
            keypadJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        add(keypadJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 330, 140));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 10, 450));

        jDesktopPane2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 350, 20));

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 10, 450));

        jDesktopPane5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 350, 40));

        jDesktopPane6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(jDesktopPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, 150));

        jDesktopPane7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jDesktopPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, -1, -1));

        jDesktopPane8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        add(jDesktopPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, -1, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void menuJlistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_menuJlistValueChanged
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_menuJlistValueChanged

    private void goJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJbuttonActionPerformed
        // TODO add your handling code here:
        
        mpinValidatorJlbl.setText("");
        mpinValidatorJlbl2.setText("");
        if(!validateForm())
            
        {
            if(authenticateUser(String.valueOf(mpinJtext.getPassword())))
            {
               
                
                 if(((String)menuJlist.getSelectedValue()).equalsIgnoreCase("Withdraw Money"))
                {
                    WithdrawMoneyJPanel withdrawMoneyJPanel = new WithdrawMoneyJPanel(userProcessContainer,userAccount);
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("withDrawMoneyJPanel",withdrawMoneyJPanel);
                    enterPinJPanel.setVisible(false);
                    mpinJtext.setText("");
                    layout.next(userProcessContainer);
                }
                
                
                
               
                
            }
        }
        
    }//GEN-LAST:event_goJbuttonActionPerformed

    private void goJbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJbutton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedIndex = menuJlist.getSelectedIndex();
        int a=1;
        if(selectedIndex>=0)
        {
         if(((String)menuJlist.getSelectedValue()).equalsIgnoreCase("Inbox"))
                {
                    CheckInboxJPanel checkInboxJPanel = new CheckInboxJPanel(userProcessContainer,userAccount);
                    
                    mpinJtext.setText("");
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("checkInboxJPanel",checkInboxJPanel);
                    layout.next(userProcessContainer);
                }
         
         
          
         
         else if(((String)menuJlist.getSelectedValue()).equalsIgnoreCase("Check Account Balance"))
                {
                    CheckAccountBalanceJPanel checkAccountBalanceJPanel = new CheckAccountBalanceJPanel(userProcessContainer,recipient);
                    
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("checkAccountBalanceJPanel",checkAccountBalanceJPanel);
                    mpinJtext.setText("");
                    layout.next(userProcessContainer);
                }
         
         else if(((String)menuJlist.getSelectedValue()).equalsIgnoreCase("Forgot MPIN"))
                {
                    
                    ForgotPasswordJPanel forgotPasswordJPanel = new ForgotPasswordJPanel(userProcessContainer,userAccount);
                   
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("forgotPasswordJPanel",forgotPasswordJPanel);
                    mpinJtext.setText("");
                    layout.next(userProcessContainer);
                }
         
         
         else if(((String)menuJlist.getSelectedValue()).equalsIgnoreCase("WithDraw Money"))
                { 
                    enterPinJPanel.setVisible(true);
        }
         
         
         
        }else
        {
            JOptionPane.showMessageDialog(displayJPanel,"Please select option from list to contine","No Selection",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_goJbutton1ActionPerformed

    private void menuJlistFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuJlistFocusGained
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_menuJlistFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ConfigureProfileJPanel configureProfileJPanel = new ConfigureProfileJPanel(userProcessContainer,userAccount);
                    
                    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                    userProcessContainer.add("configureProfileJPanel",configureProfileJPanel);
                    
                    layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane displayJPanel;
    private javax.swing.JLayeredPane enterPinJPanel;
    private javax.swing.JButton goJbutton;
    private javax.swing.JButton goJbutton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane keypadJPanel;
    private javax.swing.JList menuJlist;
    private javax.swing.JPasswordField mpinJtext;
    private javax.swing.JLabel mpinValidatorJlbl;
    private javax.swing.JLabel mpinValidatorJlbl2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
