/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Recipient;

import Business.Payment.Payment;
import Business.Person.Person;
import Business.Recipient.Recipient;
import Business.Transaction.Transactions;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class WithdrawMoneyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WithdrawMoneyJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Person person;
    private Recipient recipient;
    public WithdrawMoneyJPanel(JPanel upc,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = userAccount;
       this.person = userAccount.getPerson();
       if(person instanceof Recipient)
           recipient = (Recipient)person;
           clearLabelText();
        welcomeJlbl.setText("Welcome "+userAccount.getUsername()+",");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayJPanel = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        agentNoJtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        secretKeyJtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        transactionIdJtext = new javax.swing.JTextField();
        backJbutton = new javax.swing.JButton();
        authenticateRecipientJbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        transactionIdValidatorJlbl = new javax.swing.JLabel();
        secretKeyValidatorJlbl = new javax.swing.JLabel();
        agentNoValidatorJlbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayJPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayJPanel.setOpaque(true);
        displayJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane3.setBackground(new java.awt.Color(102, 204, 255));
        jLayeredPane3.setOpaque(true);
        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERADICATE POVERTY");
        jLayeredPane3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 26));

        jLabel2.setText("Share Happiness");
        jLayeredPane3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        displayJPanel.add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 54));

        welcomeJlbl.setText("jLabel4");
        displayJPanel.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Agent no:");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, 22));
        jLayeredPane1.add(agentNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, 30));

        jLabel4.setText("Transaction id:");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jLayeredPane1.add(secretKeyJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, 32));

        jLabel5.setText("Secret key:");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        jLayeredPane1.add(transactionIdJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 32));

        backJbutton.setText("<< BACK");
        backJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbuttonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        authenticateRecipientJbutton.setText("AUTHENTICATE RECIPIENT");
        authenticateRecipientJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateRecipientJbuttonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(authenticateRecipientJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("WITHDRAW MONEY");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        transactionIdValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        transactionIdValidatorJlbl.setText("jLabel10");
        jLayeredPane1.add(transactionIdValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        secretKeyValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        secretKeyValidatorJlbl.setText("jLabel10");
        jLayeredPane1.add(secretKeyValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        agentNoValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        agentNoValidatorJlbl.setText("jLabel10");
        jLayeredPane1.add(agentNoValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        displayJPanel.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 340, 430));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("***Please do not share your MPIN with anyone");
        displayJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 280, -1));

        add(displayJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 370, 540));
    }// </editor-fold>//GEN-END:initComponents

    public void clearLabelText()
    {
        agentNoValidatorJlbl.setText("");
        transactionIdValidatorJlbl.setText("");
  //      mpinValidatorJlbl.setText("");
        secretKeyValidatorJlbl.setText("");
    //    recipientIdValidatorJlbl.setText("");
    }
    
    private void backJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbuttonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJbuttonActionPerformed

    private void authenticateRecipientJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateRecipientJbuttonActionPerformed
        // TODO add your handling code here:
        clearLabelText();
        boolean authenticateError=false;
        
        if(!validateForm())
        {
            Payment payment = authenticateTransactionId(transactionIdJtext.getText().trim());
            if(payment.equals(null))
            {
                authenticateError=true;
                transactionIdValidatorJlbl.setText("Incorrect transaction id.");
            }
            else
            {
                if(payment.getLocalAgent().getId()!=(Integer.parseInt(agentNoJtext.getText().trim())))
                {
                    authenticateError=true;
                    agentNoValidatorJlbl.setText("Incorrect Agent no.");
                    
                }
                
//                if(!recipient.getMpin().equalsIgnoreCase(mpinJtext.getText().trim()))
//                {
//                    authenticateError=true;
//                    mpinValidatorJlbl.setText("Incorrect MPIN");
//                }
                
                if(!recipient.getStartKey().equalsIgnoreCase(secretKeyJtext.getText().trim()))
                {
                    authenticateError=true;
                    secretKeyValidatorJlbl.setText("Incorrect secret key");
                }
                
//                if(!recipient.getUniqueId().equalsIgnoreCase(recipientIdJtext.getText().trim()))
//                {
//                    authenticateError=true;
//                    recipientIdValidatorJlbl.setText("Incorrect recipient Id");
//                }
                
              }
            
            if(!authenticateError)
            {
                recipient.getMobileAccount().setAccountBalance(payment.getAmount());
                userAccount.getWorkQueue().getWorkRequestList().remove(payment);
                recipient.getMobileAccount().setAccountBalance(payment.getAmount());
                payment.setStatus(Payment.paymentStatus.RECEIVED.getValue());
                Transactions transaction = new Transactions();
                transaction.setPayment(payment);
                payment.getLocalAgent().getAgentTransactionsList().getTransactionList().add(transaction);
                AcknowledgeDonorJPanel acknowledgeDonorJPanel = new AcknowledgeDonorJPanel(userProcessContainer,userAccount,payment);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                userProcessContainer.add("acknowledgeDonorJPanel",acknowledgeDonorJPanel);
                
                layout.next(userProcessContainer);
                
            }
            
            
            
        }
        
        
        
    }//GEN-LAST:event_authenticateRecipientJbuttonActionPerformed

    
    public boolean validateForm()
    {
        boolean errorFlag=false;
        if(!Validation.validateTextFieldsForInteger(agentNoJtext))
        {
            errorFlag=true;
            agentNoValidatorJlbl.setText("Please enter valid agent no");
            
        }
        
        if(!Validation.validateTextFieldsForInteger(transactionIdJtext))
        {
            errorFlag=true;
            transactionIdValidatorJlbl.setText("Please enter valid transaction id");
        }
        
        if(!Validation.validateTextFieldsForString(secretKeyJtext))
        {
            errorFlag=true;
            secretKeyValidatorJlbl.setText("Please enter valid secret key");
        }
        
//        if(!Validation.validateTextFieldsForInteger(mpinJtext))
//        {
//            errorFlag=true;
//            mpinValidatorJlbl.setText("Please enter valid mpin");
//        }
        
//        if(!Validation.validateTextFieldsForInteger(recipientIdJtext))
//        {
//            errorFlag=true;
//            recipientIdValidatorJlbl.setText("Please enter valid recipient id");
//        }
        
    
    return errorFlag;
    }

    
    public Payment authenticateTransactionId(String transactionId)
    {
        for(WorkRequest workRequest:userAccount.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof Payment)
            {
                Payment payment = (Payment)workRequest;
                if(payment.getPaymentId()==(Integer.parseInt(transactionId)))
                {
                   return payment;
                }
            }
        }
        
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agentNoJtext;
    private javax.swing.JLabel agentNoValidatorJlbl;
    private javax.swing.JButton authenticateRecipientJbutton;
    private javax.swing.JButton backJbutton;
    private javax.swing.JLayeredPane displayJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JTextField secretKeyJtext;
    private javax.swing.JLabel secretKeyValidatorJlbl;
    private javax.swing.JTextField transactionIdJtext;
    private javax.swing.JLabel transactionIdValidatorJlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
