/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.EnrollmentOrganization;

import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollmentWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class ProcessEnrollmentRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessEnrollmentRequestJpanel
     */
    
    private JPanel userProcessContainer;
    private EnrollmentWorkRequest enrollmentWorkRequest;
    private UserAccount userAccount;
    public ProcessEnrollmentRequestJpanel(JPanel upc,EnrollmentWorkRequest enrWR,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=upc;
        this.enrollmentWorkRequest=enrWR;
        requestOwnerJlbl.setText(String.valueOf(enrollmentWorkRequest.getRequestId()));
        requestDateJlbl.setText(String.valueOf(enrollmentWorkRequest.getRequestDate()));
        this.userAccount=userAccount;
        populateAllFields();
        
        if(userAccount.getRole().equals(Role.RoleType.ENTERPRISEADMIN)||enrollmentWorkRequest.getStatus().equalsIgnoreCase("Approved")||enrollmentWorkRequest.getStatus().equalsIgnoreCase("Rejected"))
        {
            populateAllEnterpriseFields();
        }
    }
    
    
    public void populateAllFields()
    {
        headFirstNameJtext1.setText(enrollmentWorkRequest.getHeadFirstName());
        headMiddleNameJtext.setText(enrollmentWorkRequest.getHeadMiddleName());
        headLastNameJtext.setText(enrollmentWorkRequest.getHeadLastName());
        headGenderJtext.setText(enrollmentWorkRequest.getHeadGender());
        headMaritalStatusJtext.setText(enrollmentWorkRequest.getHeadMaritalStatus());
        headEducationJtext.setText(enrollmentWorkRequest.getEducationStatus());
        headSchoolNameJtext.setText(enrollmentWorkRequest.getSchoolName());
        headSchoolDetailsJtext.setText(enrollmentWorkRequest.getSchoolDetails());
        headProfessionJtext.setText(enrollmentWorkRequest.getEmploymentStatus());
        headEmployerJtext.setText(enrollmentWorkRequest.getEmployerName());
        headEmployerDetailsJtext.setText(enrollmentWorkRequest.getEmployerDetails());
        headDailyIncomeJtext.setText(enrollmentWorkRequest.getDailyIncome());
        headCellPhoneNo.setText(String.valueOf(enrollmentWorkRequest.getCellPhoneNo()));
        noOfMembersJtext.setText(String.valueOf(enrollmentWorkRequest.getNoOfMembers()));
        noOfAdultsJtext.setText(String.valueOf(enrollmentWorkRequest.getNoOfAdults()));
        noOfWomenJtext.setText(String.valueOf(enrollmentWorkRequest.getNoOfChildren()));
        spouseNameJtext.setText(enrollmentWorkRequest.getSpouseName());
        homeTypeJtext.setText(enrollmentWorkRequest.isMudHome());
        districtNameJtext.setText(enrollmentWorkRequest.getDistrictName());
        villageNameJtext.setText(String.valueOf(enrollmentWorkRequest.getVillageName()));
        fieldStaffIdJtext.setText(String.valueOf(enrollmentWorkRequest.getUserIdFieldStaff().getPerson().getId()));
        fieldStaffUsernameJtext.setText(enrollmentWorkRequest.getUserIdFieldStaff().getUsername());
       
        
    }
    
    public void populateAllEnterpriseFields()
    {
        decisionComboBox.setEnabled(false);
        approveCheckBox.setVisible(false);
        decisionJbutton.setVisible(false);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestDateJlbl = new javax.swing.JLabel();
        requestOwnerJlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        headMiddleNameJtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        headMaritalStatusJtext = new javax.swing.JTextField();
        headLastNameJtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        headFirstNameJtext1 = new javax.swing.JTextField();
        headEducationJtext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        headGenderJtext = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        headSchoolNameJtext = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        headSchoolDetailsJtext = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(32767, 6));
        jLabel12 = new javax.swing.JLabel();
        headCellPhoneNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        headEmployerJtext = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        headEmployerDetailsJtext = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        headDailyIncomeJtext = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        headProfessionJtext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        noOfMembersJtext = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        noOfAdultsJtext = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        noOfWomenJtext = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        spouseNameJtext = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        homeTypeJtext = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        districtNameJtext = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        villageNameJtext = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fieldStaffIdJtext = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        fieldStaffUsernameJtext = new javax.swing.JTextField();
        decisionComboBox = new javax.swing.JComboBox();
        approveCheckBox = new javax.swing.JCheckBox();
        decisionJbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backJbutton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(requestDateJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 230, 22));
        add(requestOwnerJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 160, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ENROLLMENT REQUEST NO.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 210, 20));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headMiddleNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headMiddleNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        headMiddleNameJtext.setEnabled(false);
        headMiddleNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headMiddleNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headMiddleNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headMiddleNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 121, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Middle Name:");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Marital Status:");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 20));

        headMaritalStatusJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headMaritalStatusJtext.setForeground(new java.awt.Color(51, 51, 51));
        headMaritalStatusJtext.setEnabled(false);
        headMaritalStatusJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headMaritalStatusJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headMaritalStatusJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headMaritalStatusJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 121, 34));

        headLastNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headLastNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        headLastNameJtext.setEnabled(false);
        headLastNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headLastNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headLastNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headLastNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 121, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Last Name:");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 80, 20));

        headFirstNameJtext1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headFirstNameJtext1.setForeground(new java.awt.Color(51, 51, 51));
        headFirstNameJtext1.setEnabled(false);
        headFirstNameJtext1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headFirstNameJtext1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headFirstNameJtext1FocusLost(evt);
            }
        });
        jLayeredPane1.add(headFirstNameJtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 121, 34));

        headEducationJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headEducationJtext.setForeground(new java.awt.Color(51, 51, 51));
        headEducationJtext.setEnabled(false);
        headEducationJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headEducationJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headEducationJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headEducationJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 121, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("First Name:");
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cell Phone no:");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Family Details");
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Gender:");
        jLayeredPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 50, 20));

        headGenderJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headGenderJtext.setForeground(new java.awt.Color(51, 51, 51));
        headGenderJtext.setEnabled(false);
        headGenderJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headGenderJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headGenderJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headGenderJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 121, 34));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("School name:");
        jLayeredPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, 20));

        headSchoolNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headSchoolNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        headSchoolNameJtext.setEnabled(false);
        headSchoolNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headSchoolNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headSchoolNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headSchoolNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 121, 34));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("School Details:");
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 80, 20));

        headSchoolDetailsJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headSchoolDetailsJtext.setForeground(new java.awt.Color(51, 51, 51));
        headSchoolDetailsJtext.setEnabled(false);
        headSchoolDetailsJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headSchoolDetailsJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headSchoolDetailsJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headSchoolDetailsJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 120, 34));
        jLayeredPane1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 66, -1, 220));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Education:");
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, 30));

        headCellPhoneNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headCellPhoneNo.setForeground(new java.awt.Color(51, 51, 51));
        headCellPhoneNo.setEnabled(false);
        headCellPhoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headCellPhoneNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headCellPhoneNoFocusLost(evt);
            }
        });
        jLayeredPane1.add(headCellPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 121, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Employer name:");
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, 20));

        headEmployerJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headEmployerJtext.setForeground(new java.awt.Color(51, 51, 51));
        headEmployerJtext.setEnabled(false);
        headEmployerJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headEmployerJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headEmployerJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headEmployerJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 120, 34));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Details:");
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 50, 20));

        headEmployerDetailsJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headEmployerDetailsJtext.setForeground(new java.awt.Color(51, 51, 51));
        headEmployerDetailsJtext.setEnabled(false);
        headEmployerDetailsJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headEmployerDetailsJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headEmployerDetailsJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headEmployerDetailsJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 120, 34));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Daily Income:");
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 30));

        headDailyIncomeJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headDailyIncomeJtext.setForeground(new java.awt.Color(51, 51, 51));
        headDailyIncomeJtext.setEnabled(false);
        headDailyIncomeJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headDailyIncomeJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headDailyIncomeJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headDailyIncomeJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 121, 34));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Profession:");
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, 30));

        headProfessionJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        headProfessionJtext.setForeground(new java.awt.Color(51, 51, 51));
        headProfessionJtext.setEnabled(false);
        headProfessionJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                headProfessionJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                headProfessionJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(headProfessionJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 121, 34));
        jLayeredPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 580, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Family Head Details");
        jLayeredPane1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("No. of Family Members:");
        jLayeredPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        noOfMembersJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noOfMembersJtext.setForeground(new java.awt.Color(51, 51, 51));
        noOfMembersJtext.setEnabled(false);
        noOfMembersJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                noOfMembersJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfMembersJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(noOfMembersJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 40, 34));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("No. of Adults:");
        jLayeredPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, 30));

        noOfAdultsJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noOfAdultsJtext.setForeground(new java.awt.Color(51, 51, 51));
        noOfAdultsJtext.setEnabled(false);
        noOfAdultsJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                noOfAdultsJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfAdultsJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(noOfAdultsJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 40, 34));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("No. of Children:");
        jLayeredPane1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 90, 30));

        noOfWomenJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noOfWomenJtext.setForeground(new java.awt.Color(51, 51, 51));
        noOfWomenJtext.setEnabled(false);
        noOfWomenJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                noOfWomenJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                noOfWomenJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(noOfWomenJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 40, 34));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Name of Spouse:");
        jLayeredPane1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 100, 30));

        spouseNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spouseNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        spouseNameJtext.setEnabled(false);
        spouseNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spouseNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spouseNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(spouseNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 121, 34));
        jLayeredPane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 580, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Location Details:");
        jLayeredPane1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Mud Thatch Home:");
        jLayeredPane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 120, 30));

        homeTypeJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        homeTypeJtext.setForeground(new java.awt.Color(51, 51, 51));
        homeTypeJtext.setEnabled(false);
        homeTypeJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeTypeJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeTypeJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(homeTypeJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 60, 34));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("District name:");
        jLayeredPane1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 90, 20));

        districtNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        districtNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        districtNameJtext.setEnabled(false);
        districtNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                districtNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                districtNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(districtNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 120, 34));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Village name:");
        jLayeredPane1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 90, 20));

        villageNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        villageNameJtext.setForeground(new java.awt.Color(51, 51, 51));
        villageNameJtext.setEnabled(false);
        villageNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                villageNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                villageNameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(villageNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 120, 34));
        jLayeredPane1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 580, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Supervisor/Field Staff Details:");
        jLayeredPane1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 210, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Employee Id:");
        jLayeredPane1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 90, 20));

        fieldStaffIdJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldStaffIdJtext.setForeground(new java.awt.Color(51, 51, 51));
        fieldStaffIdJtext.setEnabled(false);
        fieldStaffIdJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldStaffIdJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldStaffIdJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(fieldStaffIdJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 120, 34));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Username:");
        jLayeredPane1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 90, 20));

        fieldStaffUsernameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldStaffUsernameJtext.setForeground(new java.awt.Color(51, 51, 51));
        fieldStaffUsernameJtext.setEnabled(false);
        fieldStaffUsernameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldStaffUsernameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldStaffUsernameJtextFocusLost(evt);
            }
        });
        jLayeredPane1.add(fieldStaffUsernameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 120, 34));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 670, 660));

        decisionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Approve", "Rejected", "Needs more verification" }));
        add(decisionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 160, 30));

        approveCheckBox.setText("I confirm that all the verifications are completed ");
        add(approveCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        decisionJbutton.setText("Process request");
        decisionJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisionJbuttonActionPerformed(evt);
            }
        });
        add(decisionJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Decision:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 50, 20));

        backJbutton.setText("<< BACK");
        backJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbuttonActionPerformed(evt);
            }
        });
        add(backJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 530, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void headLastNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headLastNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headLastNameJtextFocusLost

    private void headLastNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headLastNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headLastNameJtextFocusGained

    private void headMaritalStatusJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headMaritalStatusJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headMaritalStatusJtextFocusLost

    private void headMaritalStatusJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headMaritalStatusJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headMaritalStatusJtextFocusGained

    private void headMiddleNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headMiddleNameJtextFocusLost
        // TODO add your handling code here:

        if(headMiddleNameJtext.getText().equals(""))
        {
            headMiddleNameJtext.setText("First name:");
            headMiddleNameJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_headMiddleNameJtextFocusLost

    private void headMiddleNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headMiddleNameJtextFocusGained
        // TODO add your handling code here:
        headMiddleNameJtext.setText("");
        headMiddleNameJtext.setForeground(Color.black);
    }//GEN-LAST:event_headMiddleNameJtextFocusGained

    private void headFirstNameJtext1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headFirstNameJtext1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headFirstNameJtext1FocusGained

    private void headFirstNameJtext1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headFirstNameJtext1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headFirstNameJtext1FocusLost

    private void headEducationJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEducationJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headEducationJtextFocusGained

    private void headEducationJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEducationJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headEducationJtextFocusLost

    private void headGenderJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headGenderJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headGenderJtextFocusGained

    private void headGenderJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headGenderJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headGenderJtextFocusLost

    private void headSchoolNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headSchoolNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headSchoolNameJtextFocusGained

    private void headSchoolNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headSchoolNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headSchoolNameJtextFocusLost

    private void headSchoolDetailsJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headSchoolDetailsJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headSchoolDetailsJtextFocusGained

    private void headSchoolDetailsJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headSchoolDetailsJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headSchoolDetailsJtextFocusLost

    private void headCellPhoneNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headCellPhoneNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headCellPhoneNoFocusGained

    private void headCellPhoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headCellPhoneNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headCellPhoneNoFocusLost

    private void headEmployerJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEmployerJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headEmployerJtextFocusGained

    private void headEmployerJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEmployerJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headEmployerJtextFocusLost

    private void headEmployerDetailsJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEmployerDetailsJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headEmployerDetailsJtextFocusGained

    private void headEmployerDetailsJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headEmployerDetailsJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headEmployerDetailsJtextFocusLost

    private void headDailyIncomeJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headDailyIncomeJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headDailyIncomeJtextFocusGained

    private void headDailyIncomeJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headDailyIncomeJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headDailyIncomeJtextFocusLost

    private void headProfessionJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headProfessionJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_headProfessionJtextFocusGained

    private void headProfessionJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_headProfessionJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_headProfessionJtextFocusLost

    private void noOfMembersJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfMembersJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfMembersJtextFocusGained

    private void noOfMembersJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfMembersJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfMembersJtextFocusLost

    private void noOfAdultsJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfAdultsJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfAdultsJtextFocusGained

    private void noOfAdultsJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfAdultsJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfAdultsJtextFocusLost

    private void noOfWomenJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfWomenJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfWomenJtextFocusGained

    private void noOfWomenJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_noOfWomenJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfWomenJtextFocusLost

    private void spouseNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameJtextFocusGained

    private void spouseNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spouseNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameJtextFocusLost

    private void homeTypeJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeTypeJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_homeTypeJtextFocusGained

    private void homeTypeJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeTypeJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_homeTypeJtextFocusLost

    private void districtNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_districtNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_districtNameJtextFocusGained

    private void districtNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_districtNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_districtNameJtextFocusLost

    private void villageNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_villageNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_villageNameJtextFocusGained

    private void villageNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_villageNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_villageNameJtextFocusLost

    private void fieldStaffIdJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldStaffIdJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStaffIdJtextFocusGained

    private void fieldStaffIdJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldStaffIdJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStaffIdJtextFocusLost

    private void fieldStaffUsernameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldStaffUsernameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStaffUsernameJtextFocusGained

    private void fieldStaffUsernameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldStaffUsernameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStaffUsernameJtextFocusLost

    private void decisionJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisionJbuttonActionPerformed
        // TODO add your handling code here:
        boolean errorFlag=false;
        if(String.valueOf(decisionComboBox.getSelectedItem()).equalsIgnoreCase("Approve"))
          {
              if(!approveCheckBox.isSelected())
              {
                  JOptionPane.showMessageDialog(null,"Please confirm if all the details are verified","Missing input",JOptionPane.ERROR_MESSAGE);
                  errorFlag=true;
                  
              }
              
              
                    
          }
        
        if(!errorFlag)
        {
        
        int answer = JOptionPane.showConfirmDialog(null," Do you want to "+String.valueOf(decisionComboBox.getSelectedItem())+" this request");
        if(answer==JOptionPane.YES_OPTION)
        {
            if(String.valueOf(decisionComboBox.getSelectedItem()).equalsIgnoreCase("Approve"))
            enrollmentWorkRequest.setStatus("Approved");
            else if(String.valueOf(decisionComboBox.getSelectedItem()).equalsIgnoreCase("Reject"))
            enrollmentWorkRequest.setStatus("Rejected");
            else
            enrollmentWorkRequest.setStatus("More verification Required");    
            enrollmentWorkRequest.setUserIdSeniorStaff(userAccount);
            enrollmentWorkRequest.setResolveDate(new Date());
            JOptionPane.showMessageDialog(null,"Request processed successfully","Request processed",JOptionPane.INFORMATION_MESSAGE);
            populateAllEnterpriseFields();
            
                   
        }
        }
    }//GEN-LAST:event_decisionJbuttonActionPerformed

    private void backJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbuttonActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox approveCheckBox;
    private javax.swing.JButton backJbutton;
    private javax.swing.JComboBox decisionComboBox;
    private javax.swing.JButton decisionJbutton;
    private javax.swing.JTextField districtNameJtext;
    private javax.swing.JTextField fieldStaffIdJtext;
    private javax.swing.JTextField fieldStaffUsernameJtext;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField headCellPhoneNo;
    private javax.swing.JTextField headDailyIncomeJtext;
    private javax.swing.JTextField headEducationJtext;
    private javax.swing.JTextField headEmployerDetailsJtext;
    private javax.swing.JTextField headEmployerJtext;
    private javax.swing.JTextField headFirstNameJtext1;
    private javax.swing.JTextField headGenderJtext;
    private javax.swing.JTextField headLastNameJtext;
    private javax.swing.JTextField headMaritalStatusJtext;
    private javax.swing.JTextField headMiddleNameJtext;
    private javax.swing.JTextField headProfessionJtext;
    private javax.swing.JTextField headSchoolDetailsJtext;
    private javax.swing.JTextField headSchoolNameJtext;
    private javax.swing.JTextField homeTypeJtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField noOfAdultsJtext;
    private javax.swing.JTextField noOfMembersJtext;
    private javax.swing.JTextField noOfWomenJtext;
    private javax.swing.JLabel requestDateJlbl;
    private javax.swing.JLabel requestOwnerJlbl;
    private javax.swing.JTextField spouseNameJtext;
    private javax.swing.JTextField villageNameJtext;
    // End of variables declaration//GEN-END:variables
}
