/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.EnrollmentOrganization;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EnrollmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.BrowserFactory;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJPL
 */
public class SeniorStaffWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeniorStaffWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private UserAccount userAccount;
    public SeniorStaffWorkAreaJPanel(JPanel upc,Organization organization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=upc;
        this.organization=organization;
        this.userAccount=userAccount;
        populateEnrollmentRequestTable();
    }
    
    public void populateEnrollmentRequestTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)enrollmentRequestJtable.getModel();
        dtm.setRowCount(0);
        
       
        
        EnrollmentWorkRequest enrollmentWorkRequest=null;
        for(WorkRequest workRequest:organization.getWorkQueue().getWorkRequestList())
        {
            System.out.println("WorkRequest"+workRequest.getRequestId());
            if(workRequest instanceof EnrollmentWorkRequest)
            {
                System.out.println("Login organization"+organization);
                enrollmentWorkRequest=(EnrollmentWorkRequest)workRequest;
                if(enrollmentWorkRequest.getStatus().equalsIgnoreCase("Requested"))
                {
                Object row[]=new Object[5];
                row[0]=enrollmentWorkRequest;
                row[1]=enrollmentWorkRequest.getUserIdFieldStaff().getUsername();
                row[2]=enrollmentWorkRequest.getHeadLastName()+","+enrollmentWorkRequest.getHeadFirstName();
                row[3]=enrollmentWorkRequest.getDistrictName()+"-"+enrollmentWorkRequest.getVillageName();
                row[4]=enrollmentWorkRequest.getRequestDate();
                dtm.addRow(row);
            }
            }   
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrollmentRequestJtable = new javax.swing.JTable();
        processRequestJbutton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SENIOR STAFF WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ENROLLMENT REQUESTS:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        enrollmentRequestJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Field Staff Username", "Name of Recipient", "Daily income", "Request Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enrollmentRequestJtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 870, 120));

        processRequestJbutton.setText("View && Process enrollment request");
        processRequestJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestJbuttonActionPerformed(evt);
            }
        });
        add(processRequestJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 240, 30));

        jButton3.setText("Verify Location of Recipient in request");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 240, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void processRequestJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestJbuttonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = enrollmentRequestJtable.getSelectedRow();
        EnrollmentWorkRequest enrollmentWorkRequest=null;
        
        if(selectedRow>=0)
        {
            
        WorkRequest workRequest = (WorkRequest)enrollmentRequestJtable.getValueAt(selectedRow,0);    
        if(workRequest instanceof EnrollmentWorkRequest)
        enrollmentWorkRequest = (EnrollmentWorkRequest)workRequest;
        ProcessEnrollmentRequestJpanel  processEnrollmentRequestJPanel=new ProcessEnrollmentRequestJpanel(userProcessContainer,enrollmentWorkRequest,userAccount);
        userProcessContainer.add("processEnrollmentRequestJPanel",processEnrollmentRequestJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select work request to view and process","No selection",JOptionPane.ERROR_MESSAGE);
                    
        }
    }//GEN-LAST:event_processRequestJbuttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRow = enrollmentRequestJtable.getSelectedRow();
        if(selectedRow>=0)
        {
        EnrollmentWorkRequest enrollmentWorkRequest=(EnrollmentWorkRequest)enrollmentRequestJtable.getValueAt(selectedRow,0);
        Browser browser = BrowserFactory.create();
        JFrame frame = new JFrame("Hello World!");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        JInternalFrame frame1 = new JInternalFrame("Hello World!");
        frame.add(frame1);
        frame1.setVisible(true);
        frame1.add(browser.getView().getComponent(), BorderLayout.CENTER);
        frame.setSize(600, 500);
        frame1.setSize(400,300);
        frame.setVisible(true);
        String lattitude = String.valueOf(enrollmentWorkRequest.getLocation().getLattitude());
        String longitude = String.valueOf(enrollmentWorkRequest.getLocation().getLongitude());

        browser.loadURL("https://www.google.com/maps?q=loc:"+lattitude+","+longitude);
        if(selectedRow>=0)
        {
            
        WorkRequest workRequest = (WorkRequest)enrollmentRequestJtable.getValueAt(selectedRow,0);    
        if(workRequest instanceof EnrollmentWorkRequest)
        enrollmentWorkRequest = (EnrollmentWorkRequest)workRequest;
         
        }
        
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select work request to verify location","No selection",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable enrollmentRequestJtable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processRequestJbutton;
    // End of variables declaration//GEN-END:variables
}
