/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.BankEnterprise;

import Business.Bank.SavingsAccount;
import Business.Donor.DonorPerson;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class BankEnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankEnterpriseAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public BankEnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        defaultText();
        
    }
    
    public void defaultText()
    {   firstNameValidatorJlbl2.setText("");
        middleNameValidatorJlbl.setText("");
        emailAddressValidatorJlbl.setText("");
        idValidatorJlbl.setText("");
        nomineeNameValidatorJlbl.setText("");
        cardNoValidatorJlbl.setText("");
        cardHolderNameValidatorJlbl.setText("");
        dateOfBirthValidatorJlbl.setText("");
        lastNameValidatorJlbl.setText("");
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createAccountJPanel = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cardHolderNameJtext = new javax.swing.JTextField();
        middleNameJtext = new javax.swing.JTextField();
        birthDateComboBox = new javax.swing.JComboBox();
        birthYearComboBox = new javax.swing.JComboBox();
        lastNameJtext = new javax.swing.JTextField();
        emailAddressJtext = new javax.swing.JTextField();
        nomineeNameJtext = new javax.swing.JTextField();
        cardTypeComboBox = new javax.swing.JComboBox();
        birthMonthComboBox = new javax.swing.JComboBox();
        cardNoJtext = new javax.swing.JTextField();
        firstNameJtext = new javax.swing.JTextField();
        idJtext = new javax.swing.JTextField();
        createAccountJbutton = new javax.swing.JButton();
        idValidatorJlbl = new javax.swing.JLabel();
        dateOfBirthValidatorJlbl = new javax.swing.JLabel();
        nomineeNameValidatorJlbl = new javax.swing.JLabel();
        cardHolderNameValidatorJlbl = new javax.swing.JLabel();
        emailAddressValidatorJlbl = new javax.swing.JLabel();
        cardNoValidatorJlbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        middleNameValidatorJlbl = new javax.swing.JLabel();
        lastNameValidatorJlbl = new javax.swing.JLabel();
        firstNameValidatorJlbl2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BANK ENTERPRISE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        createAccountJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createAccountJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Create new Savings Account");
        createAccountJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));
        createAccountJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 34, 860, 10));

        cardHolderNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardHolderNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardHolderNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardHolderNameJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(cardHolderNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 270, 34));

        middleNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        middleNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(middleNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 121, 34));
        middleNameJtext.getAccessibleContext().setAccessibleName("middleNameJtext");

        birthDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        createAccountJPanel.add(birthDateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 30));

        birthYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004" }));
        createAccountJPanel.add(birthYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 30));

        lastNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(lastNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 121, 34));
        lastNameJtext.getAccessibleContext().setAccessibleName("lastNameJtext");

        emailAddressJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailAddressJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailAddressJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailAddressJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(emailAddressJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 270, 34));

        nomineeNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomineeNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        nomineeNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomineeNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomineeNameJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(nomineeNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 270, 34));

        cardTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit", "Credit" }));
        createAccountJPanel.add(cardTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 210, 30));

        birthMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        createAccountJPanel.add(birthMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 30));
        birthMonthComboBox.getAccessibleContext().setAccessibleName("birthMonthComboBox");

        cardNoJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardNoJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNoJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNoJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(cardNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 270, 34));

        firstNameJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(firstNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 121, 34));
        firstNameJtext.getAccessibleContext().setAccessibleName("firstNameJtext");

        idJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idJtextFocusLost(evt);
            }
        });
        createAccountJPanel.add(idJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 270, 34));

        createAccountJbutton.setText("CREATE ACCOUNT>>");
        createAccountJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountJbuttonActionPerformed(evt);
            }
        });
        createAccountJPanel.add(createAccountJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 170, 30));

        idValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(idValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 170, -1));

        dateOfBirthValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(dateOfBirthValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 320, 20));

        nomineeNameValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(nomineeNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, -1));

        cardHolderNameValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(cardHolderNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 170, -1));

        emailAddressValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(emailAddressValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 170, -1));

        cardNoValidatorJlbl.setText("jLabel3");
        createAccountJPanel.add(cardNoValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 170, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Last name:");
        createAccountJPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Email Address:");
        createAccountJPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Unique id:");
        createAccountJPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));
        createAccountJPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 610, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Nominee Name:");
        createAccountJPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Card type:");
        createAccountJPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Card no:");
        createAccountJPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("CardHolder name:");
        createAccountJPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Date of Birth:");
        createAccountJPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("First name:");
        createAccountJPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Middle name:");
        createAccountJPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));
        createAccountJPanel.add(middleNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 260, 20));
        createAccountJPanel.add(lastNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 200, 20));
        createAccountJPanel.add(firstNameValidatorJlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 170, 20));

        add(createAccountJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 860, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void cardHolderNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardHolderNameJtextFocusGained
        // TODO add your handling code here:
        cardHolderNameJtext.setText("");
        cardHolderNameJtext.setForeground(Color.black);
    }//GEN-LAST:event_cardHolderNameJtextFocusGained

    private void cardHolderNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardHolderNameJtextFocusLost
        // TODO add your handling code here:

        if(cardHolderNameJtext.getText().equals(""))
        {
            cardHolderNameJtext.setText("First name:");
            cardHolderNameJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_cardHolderNameJtextFocusLost

    private void middleNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameJtextFocusGained

    private void middleNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameJtextFocusLost

    private void lastNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJtextFocusGained

    private void lastNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJtextFocusLost

    private void emailAddressJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAddressJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressJtextFocusGained

    private void emailAddressJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAddressJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressJtextFocusLost

    private void nomineeNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomineeNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nomineeNameJtextFocusGained

    private void nomineeNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomineeNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nomineeNameJtextFocusLost

    private void cardNoJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNoJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNoJtextFocusGained

    private void cardNoJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNoJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNoJtextFocusLost

    private void firstNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJtextFocusGained

    private void firstNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameJtextFocusLost

    private void idJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idJtextFocusGained

    private void idJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idJtextFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idJtextFocusLost

    private void createAccountJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountJbuttonActionPerformed
        // TODO add your handling code here:
       defaultText();
       
        if(!validateForm())
        {
            
          DonorPerson donorPerson = new DonorPerson();
          donorPerson.setFirstName(firstNameJtext.getText().trim());
          donorPerson.setLastName(lastNameJtext.getText().trim());
          donorPerson.setMiddleName(middleNameJtext.getText().trim());
          donorPerson.setEmailId(emailAddressJtext.getText().trim());
          donorPerson.setUniqueId(idJtext.getText());
          
          
          // code to extract dateofBirth
          
          String birthDate = String.valueOf(birthDateComboBox.getSelectedItem());
          String birthMonth = String.valueOf(birthMonthComboBox.getSelectedItem());
          String birthYear = String.valueOf(birthYearComboBox.getSelectedItem());
          
          SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");  
        Date dateOfBirth = null;  
        String date = birthMonth+"/"+birthDate+"/"+birthYear;  
        try{  
            dateOfBirth = df.parse(date);
            
            donorPerson.setDateOfBirth(dateOfBirth);
            
        } catch (Exception e){ System.out.println("invalid format");}  
          
        if (!df.format(dateOfBirth).equals(date)){  
            System.out.println("invalid date!!");  
        } else {  
            System.out.println("valid date"); }
          
          SavingsAccount donorAccount = new SavingsAccount();
          donorAccount.setAccountHolder(donorPerson);
          try
          {
             // donorAccount.setCardNo(Integer.parseInt(cardNoJtext.getText().trim()));
          }
          
          catch(Exception e)
          {
              System.out.println("Exception caught"+e);
          }
          //donorAccount.setCardHolderName(cardHolderNameJtext.getText().trim());
          
          Calendar calendar = new GregorianCalendar();
          calendar.add(Calendar.MONTH,3);
          calendar.add(Calendar.YEAR,5);
          //donorAccount.setExpiryDate(calendar.getTime());
            System.out.println(calendar.getTime());
          JOptionPane.showMessageDialog(null,"New Savings account for"+firstNameJtext.getText()+lastNameJtext.getText()+"is created successfully");
          defaultText();
          clearFormFields();
          
        }
    }//GEN-LAST:event_createAccountJbuttonActionPerformed

    
    public void clearFormFields()
    {
        firstNameJtext.setText("");
        lastNameJtext.setText("");
        middleNameJtext.setText("");
        emailAddressJtext.setText("");
        
    }
    
    public boolean validateForm()
    {
        boolean errorFlag=false;
        
        if(!Validation.validateTextFieldsForNonEmpty(firstNameJtext)||!Validation.validateTextFieldsForString(firstNameJtext))
        {
            errorFlag=true;
            firstNameValidatorJlbl2.setForeground(Color.red);
            firstNameValidatorJlbl2.setText("Please enter valid first name");
        }
        
        
        if(!Validation.validateTextFieldsForNonEmpty(lastNameJtext)||!Validation.validateTextFieldsForString(lastNameJtext))
        {
            errorFlag=true;
            lastNameValidatorJlbl.setForeground(Color.red);
            lastNameValidatorJlbl.setText("Please enter valid last name");
        }
        
        
        if(!Validation.validateTextFieldsForString(middleNameJtext))
        {
            errorFlag=true;
            middleNameValidatorJlbl.setForeground(Color.red);
            middleNameValidatorJlbl.setText("Please enter valid middle name");
        }
        
        if(!Validation.validateTextFieldsForNonEmpty(emailAddressJtext)||!Validation.validateTextFieldsForEmailId(emailAddressJtext))
        {
            errorFlag=true;
            emailAddressValidatorJlbl.setForeground(Color.red);
            emailAddressValidatorJlbl.setText("Please enter valid email id");
        }
        
        if(!Validation.validateTextFieldsForNonEmpty(idJtext)||!Validation.validateTextFieldsForString(idJtext))
        {
            errorFlag=true;
            idValidatorJlbl.setForeground(Color.red);
            idValidatorJlbl.setText("Please enter valid unique id");
        }
        
        if(!Validation.validateTextFieldsForNonEmpty(cardNoJtext)||!Validation.validateTextFieldsForNumber(cardNoJtext))
        {
            errorFlag=true;
            cardNoValidatorJlbl.setForeground(Color.red);
            cardNoValidatorJlbl.setText("Please enter valid card no.");
        }
        
        if(String.valueOf(birthDateComboBox.getSelectedItem()).equalsIgnoreCase("DD")||String.valueOf(birthMonthComboBox.getSelectedItem()).equalsIgnoreCase("MM")||String.valueOf(birthYearComboBox.getSelectedItem()).equalsIgnoreCase("YYYY"))
        {
            errorFlag=true;
            dateOfBirthValidatorJlbl.setForeground(Color.red);
            dateOfBirthValidatorJlbl.setText("Please enter valid date for Date of Birth");
        }
        
        
        
        
        
        return errorFlag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox birthDateComboBox;
    private javax.swing.JComboBox birthMonthComboBox;
    private javax.swing.JComboBox birthYearComboBox;
    private javax.swing.JTextField cardHolderNameJtext;
    private javax.swing.JLabel cardHolderNameValidatorJlbl;
    private javax.swing.JTextField cardNoJtext;
    private javax.swing.JLabel cardNoValidatorJlbl;
    private javax.swing.JComboBox cardTypeComboBox;
    private javax.swing.JLayeredPane createAccountJPanel;
    private javax.swing.JButton createAccountJbutton;
    private javax.swing.JLabel dateOfBirthValidatorJlbl;
    private javax.swing.JTextField emailAddressJtext;
    private javax.swing.JLabel emailAddressValidatorJlbl;
    private javax.swing.JTextField firstNameJtext;
    private javax.swing.JLabel firstNameValidatorJlbl2;
    private javax.swing.JTextField idJtext;
    private javax.swing.JLabel idValidatorJlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameJtext;
    private javax.swing.JLabel lastNameValidatorJlbl;
    private javax.swing.JTextField middleNameJtext;
    private javax.swing.JLabel middleNameValidatorJlbl;
    private javax.swing.JTextField nomineeNameJtext;
    private javax.swing.JLabel nomineeNameValidatorJlbl;
    // End of variables declaration//GEN-END:variables
}
