/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Government;

import Business.Enterprise.Enterprise;
import Business.GovernmentEnterprise.Government;
import Business.GovernmentEnterprise.Region;
import Business.GovernmentEnterprise.Village;
import Business.Utility.Validation;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author JJPL
 */
public class GovernmentAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentAdminJPanel
     */
    
    private final String COUNTRY="Please select country";
    private final String STATE="Please select state";
    private final String VILLAGENAME ="Village name:";
    private final String VILLAGEBPL="Village Poverty Line";
    
    private JPanel userProcessContainer;
    private Government government;
    public GovernmentAdminJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        if(enterprise instanceof Government)
        government = (Government)enterprise;
        hideJPanels();
        //populateCountryComboBox();
        titleJlbl.setText(government.getName());
        populateStateComboBox();
        clearFormFields();
        
        
    }
    //hide JPanels
    
    public void hideJPanels()
    {
        addVillageJPanel.setVisible(false);
        addStateJPanel.setVisible(false);
    }
    //populate Country combo box

    
    
    //populate State combo box
    
    public void populateStateComboBox()
    {
        stateComboBox.removeAllItems();
        for(Region region:government.getRegionDirectory().getRegionList())
        {
            stateComboBox.addItem(region);
        }
    }
    
    //populate village table
    
    public void populateVillageTable(Region state)
    {
        DefaultTableModel dtm = (DefaultTableModel)villagesJtable.getModel();
        dtm.setRowCount(0);
        
        for(Region region:government.getRegionDirectory().getRegionList())
        {
            if(region.equals(state))
            {
                for(Village village:region.getVillageList())
                {
                    Object row[]=new Object[4];
                    row[0]=village.getVillageCode();
                    row[1]=village;
                    row[2]=village.getVillageBPL();
                    row[3]=village.getPercentPersonsBPL();
                    dtm.addRow(row);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        villagesJtable = new javax.swing.JTable();
        stateComboBox = new javax.swing.JComboBox();
        addVillageJbutton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addVillageJPanel = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        villageNameJtext = new javax.swing.JTextField();
        villagePovertyLineJtext = new javax.swing.JTextField();
        personBPLJSpinner = new javax.swing.JSpinner();
        addJbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        villageNameValidatorJlabel = new javax.swing.JLabel();
        personBPLValidatorJLabel = new javax.swing.JLabel();
        villageNameValidatorJlbl = new javax.swing.JLabel();
        villageBPLValidatorJlbl = new javax.swing.JLabel();
        personBPLValidatorJlbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addStateJPanel = new javax.swing.JLayeredPane();
        stateNameJtext = new javax.swing.JTextField();
        addStateJbutton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        titleJlbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        villagesJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Village Code", "Village name", "Poverty line", "% of persons(bpl)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(villagesJtable);

        stateComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        stateComboBox.setForeground(new java.awt.Color(204, 204, 204));
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select state" }));
        stateComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateComboBoxFocusGained(evt);
            }
        });
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        addVillageJbutton.setText("Add New Village");
        addVillageJbutton.setEnabled(false);
        addVillageJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVillageJbuttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("VILLAGE CENSUS");

        jButton1.setText("Add new State");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 279, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(174, 174, 174))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addVillageJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(addVillageJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stateComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addVillageJbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 570, 470));

        addVillageJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        addVillageJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addVillageJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("      ADD VILLAGE");
        addVillageJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 10, 135, -1));

        villageNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                villageNameJtextFocusGained(evt);
            }
        });
        addVillageJPanel.add(villageNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 54, 194, 32));

        villagePovertyLineJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                villagePovertyLineJtextFocusGained(evt);
            }
        });
        addVillageJPanel.add(villagePovertyLineJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 194, 32));
        addVillageJPanel.add(personBPLJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 50, 29));

        addJbutton.setText("Add");
        addJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJbuttonActionPerformed(evt);
            }
        });
        addVillageJPanel.add(addJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 297, 220, 30));

        jLabel3.setText("%");
        addVillageJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel4.setText("% persons(BPL):");
        addVillageJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 102, -1));

        villageNameValidatorJlabel.setForeground(new java.awt.Color(255, 51, 51));
        addVillageJPanel.add(villageNameValidatorJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 194, -1, 15));

        personBPLValidatorJLabel.setForeground(new java.awt.Color(255, 51, 51));
        addVillageJPanel.add(personBPLValidatorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 10));

        villageNameValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        villageNameValidatorJlbl.setText("jLabel1");
        addVillageJPanel.add(villageNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 250, -1));

        villageBPLValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        villageBPLValidatorJlbl.setText("jLabel1");
        addVillageJPanel.add(villageBPLValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, -1));

        personBPLValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        personBPLValidatorJlbl.setText("jLabel1");
        addVillageJPanel.add(personBPLValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, -1));

        add(addVillageJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 310, 340));
        addVillageJPanel.getAccessibleContext().setAccessibleName("addVillageJPanel");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*BPL - Below Poverty Line");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        addStateJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        addStateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stateNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        stateNameJtext.setText("State name:");
        stateNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateNameJtextFocusGained(evt);
            }
        });
        addStateJPanel.add(stateNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 60, 220, 28));

        addStateJbutton.setText("Add State");
        addStateJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStateJbuttonActionPerformed(evt);
            }
        });
        addStateJPanel.add(addStateJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 114, 216, -1));
        addStateJPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 306, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Add new state");
        addStateJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 84, -1));

        add(addStateJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 310, 150));

        jLayeredPane2.setBackground(new java.awt.Color(51, 153, 255));
        jLayeredPane2.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Eradicate Poverty");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Share happiness");

        titleJlbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel9)))
                .addGap(143, 143, 143)
                .addComponent(titleJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(titleJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jButton2.setText("View Maps");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
        
        Region selectedState = (Region)stateComboBox.getSelectedItem();
        if(!String.valueOf(stateComboBox.getSelectedItem()).equals(STATE))
        {
            addVillageJbutton.setEnabled(true);
            populateVillageTable(selectedState);
        }
        
        
        
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void stateNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateNameJtextFocusGained
        // TODO add your handling code here:
        
        stateNameJtext.setText("");
        stateNameJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_stateNameJtextFocusGained

    private void stateComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateComboBoxFocusGained
        // TODO add your handling code here:
        stateComboBox.removeItem(STATE);
        stateComboBox.setForeground(Color.BLACK);
                
    }//GEN-LAST:event_stateComboBoxFocusGained

    private void addVillageJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVillageJbuttonActionPerformed
        // TODO add your handling code here:
        
        //Region selectedState = (Region)stateComboBox.getSelectedItem();
        addStateJPanel.setVisible(false);
        
        if(stateComboBox.getSelectedItem().equals(STATE))
        {
            JOptionPane.showMessageDialog(null,"Please select state to add village");
        }
        addVillageJPanel.setVisible(true);
        
        villageNameJtext.setText(VILLAGENAME);
        villagePovertyLineJtext.setText(VILLAGEBPL);
        villageNameJtext.setForeground(Color.LIGHT_GRAY);
        villagePovertyLineJtext.setForeground(Color.LIGHT_GRAY);
        
        
    }//GEN-LAST:event_addVillageJbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addStateJPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void villageNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_villageNameJtextFocusGained
        // TODO add your handling code here:
        villageNameJtext.setText("");
        villageNameJtext.setForeground(Color.black);
    }//GEN-LAST:event_villageNameJtextFocusGained

    private void villagePovertyLineJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_villagePovertyLineJtextFocusGained
        // TODO add your handling code here:
        
        villagePovertyLineJtext.setText("");
        villagePovertyLineJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_villagePovertyLineJtextFocusGained

    private void addJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        
        
        if(!Validation.validateTextFieldsForNonEmpty(villageNameJtext)||villageNameJtext.getText().trim().equalsIgnoreCase(VILLAGENAME))
        {
            errorFlag=true;
            villageNameValidatorJlbl.setText("Please enter village name");
        }
        
        else if(!Validation.validateTextFieldsForString(villageNameJtext))
        {
            errorFlag=true;
            villageNameValidatorJlbl.setText("Please enter valid village name");
        }
        
        if(!Validation.validateTextFieldsForNonEmpty(villagePovertyLineJtext)||villagePovertyLineJtext.getText().trim().equalsIgnoreCase(VILLAGEBPL))
        {
            errorFlag=true;
            villageBPLValidatorJlbl.setText("Please enter Village BPL value");
        }
        
        if(!Validation.validateTextFieldsForInteger(villagePovertyLineJtext))
        {
            errorFlag=true;
            villageBPLValidatorJlbl.setText("Please enter valid Village BPL value");
        }
        
        if((Integer)(personBPLJSpinner.getValue())<=0)
        {
            errorFlag=true;
            personBPLValidatorJlbl.setText("Please enter % of persons(bpl)");
        }
        
        if(!errorFlag)
        {
            Region selectedState = (Region)stateComboBox.getSelectedItem();
            
            if(selectedState.checkUniqueVillage(villageNameJtext.getText().trim()))
            {
            selectedState.addVillage(villageNameJtext.getText().trim(),Integer.parseInt(villagePovertyLineJtext.getText().trim()),(Integer)(personBPLJSpinner.getValue()));
            populateVillageTable(selectedState);
            clearFormFields();
            
            }
            
            else
                
            {
                JOptionPane.showMessageDialog(null,"Sorry, village "+villageNameJtext.getText()+" is already added to state "+selectedState.getRegionName(),"Duplicate entry",JOptionPane.ERROR_MESSAGE);
            }
        }
        
      
        
        
    }//GEN-LAST:event_addJbuttonActionPerformed

    private void addStateJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStateJbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        
        if(!Validation.validateTextFieldsForNonEmpty(stateNameJtext)||stateNameJtext.getText().trim().equalsIgnoreCase("State name:"))
        {
            errorFlag=true;
            JOptionPane.showMessageDialog(null,"Please enter state name");
            return;
        }
        
        else
        {
           if(government.getRegionDirectory().checkUniqueRegion(stateNameJtext.getText()))
           {
           Region addedRegion= government.getRegionDirectory().addRegion();
           addedRegion.setRegionName(stateNameJtext.getText().trim());
           JOptionPane.showMessageDialog(null,"State "+stateNameJtext.getText()+" is created successfully");
           populateStateComboBox();
           return; 
           }
           
           else
           {
               JOptionPane.showMessageDialog(null,"Sorry, state "+stateNameJtext.getText()+" is already added in network","Duplicate entry",JOptionPane.ERROR_MESSAGE);
               return;
           }
           
        }
    }//GEN-LAST:event_addStateJbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ChartPanel chart1;
        Region selectedRegion = (Region)stateComboBox.getSelectedItem();
        
         try {
              
              DefaultCategoryDataset line_chart_dataset1 = new DefaultCategoryDataset();
              
                for (Village village :selectedRegion.getVillageList())
                {
                  int percentBPL = village.getPercentPersonsBPL();
                  int personBPL = village.getVillageBPL();
                 
                  line_chart_dataset1.addValue(personBPL,"Percent BPL",village.getVillageName());
                  line_chart_dataset1.addValue(percentBPL,"Person BPL",village.getVillageName());
                  
                  
                  
                 JFreeChart lineChartObject1=ChartFactory.createLineChart3D("Village List","Statistics","VitalSign Count",line_chart_dataset1,PlotOrientation.VERTICAL,true,true,false);
                 chart1 = new ChartPanel (lineChartObject1);  
                
                                
                 
                 chart1.setLayout(new BorderLayout());
                 chart1.setMouseWheelEnabled(true);
                 chart1.setVisible(true);
                 chart1.setPreferredSize(new java.awt.Dimension(500, 270));
                 
                 JFrame jframe = new JFrame();
                 jframe.add(chart1);
                 jframe.setVisible(true);
                 
                 
                 
                 
                 
                
                 
                 
                 
                
                 
                 
                 
                }  
                
                
         }
         catch (Exception i)
         {
             System.out.println(i);
         }
     
      
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void clearFormFields()
    {
        
        villageBPLValidatorJlbl.setText("");
        villageNameValidatorJlbl.setText("");
        villageNameJtext.setText(VILLAGENAME);
        villagePovertyLineJtext.setText(VILLAGEBPL);
        personBPLValidatorJlbl.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJbutton;
    private javax.swing.JLayeredPane addStateJPanel;
    private javax.swing.JButton addStateJbutton;
    private javax.swing.JLayeredPane addVillageJPanel;
    private javax.swing.JButton addVillageJbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner personBPLJSpinner;
    private javax.swing.JLabel personBPLValidatorJLabel;
    private javax.swing.JLabel personBPLValidatorJlbl;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JTextField stateNameJtext;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JLabel villageBPLValidatorJlbl;
    private javax.swing.JTextField villageNameJtext;
    private javax.swing.JLabel villageNameValidatorJlabel;
    private javax.swing.JLabel villageNameValidatorJlbl;
    private javax.swing.JTextField villagePovertyLineJtext;
    private javax.swing.JTable villagesJtable;
    // End of variables declaration//GEN-END:variables
}
