/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.EnterpriseAdmin;

import Business.Employee.Employee;
import Business.Enterprise.DonationEnterprise;
import Business.Enterprise.Enterprise;
import Business.GovernmentEnterprise.Government;
import Business.GovernmentEnterprise.Region;
import Business.GovernmentEnterprise.Village;
import Business.LocalAgent.LocalAgent;
import Business.MobileEnterprise.MobileEnterprise;
import Business.Organization.EnrollmentOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Recipient.Recipient;
import Business.Role.AccountsManagerRole;
import Business.Role.OrganizationAdminRole;
import Business.Role.RecipientRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import Business.WorkQueue.EnrollmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import business.utility.SendEmail;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.EnrollmentOrganization.ProcessEnrollmentRequestJpanel;

/**
 *
 * @author JJPL
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private Government government;
    private final String ORGANIZATION="Please select Organization type";
    DonationEnterprise donationEnterprise = null;
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=account;
       welcomeAdminJlbl.setText("Welcome "+userAccount.getUsername()+" ,");
        enterpriseName_Jlabel.setText("Enterprise - "+enterprise);
        populateOrganizationComboBox();
        manageOrganizationAdminJPanel.setVisible(false);
       
        populateOrganizationTable(enterprise);
        
       // populateEnterpriseTypeComboBox();
        
        
        if(enterprise instanceof DonationEnterprise)
        {
            donationEnterprise = (DonationEnterprise)enterprise;
            populateAssociatedEnterprise();
        }
        
        populateApprovedEnrollmentRequestTable();
        //populateVillageComboBox();
        populateLocalAgentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        manageReportJTabbedPane = new javax.swing.JTabbedPane();
        manageOrganizationJTabbedPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJtable = new javax.swing.JTable();
        addOrganizationJPanel = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        organizationName_Jtext = new javax.swing.JTextField();
        organizationComboBox = new javax.swing.JComboBox();
        addOrganization_Jbutton = new javax.swing.JButton();
        organizationTypeValidator_Jlabel = new javax.swing.JLabel();
        organizationNameValidator_Jlabel1 = new javax.swing.JLabel();
        addOrganizationAdmin_Jbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        manageOrganizationAdminJPanel = new javax.swing.JLayeredPane();
        jSeparator2 = new javax.swing.JSeparator();
        addOrganizationAdmin_Jlabel = new javax.swing.JLabel();
        organizationAdminUserName_Jtext = new javax.swing.JTextField();
        organizationAdminEmailId_Jtext = new javax.swing.JTextField();
        addAdmin_Jbutton = new javax.swing.JButton();
        adminNameValidator_Jlabel = new javax.swing.JLabel();
        adminEmailIdValidator_Jlabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        organizationAdminJtable = new javax.swing.JTable();
        adminLastNameValidatorJlbl = new javax.swing.JLabel();
        adminLastNameJtext = new javax.swing.JTextField();
        adminFirstNameValidatorJlbl = new javax.swing.JLabel();
        manageLocalAgentJTabbedPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        agentDirectoryJtable = new javax.swing.JTable();
        viewAgentProfileJbutton = new javax.swing.JButton();
        manageExternalEnterpriseJTabbedPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        associatedEnterpriseJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        reportJTabbedPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        approvedRequestsJtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        enterpriseAdminNameJlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseAdminName_Jlabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enterpriseName_Jlabel = new javax.swing.JLabel();
        welcomeAdminJlbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageReportJTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        manageOrganizationJTabbedPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        manageOrganizationJTabbedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization id:", "Organization name", "Organization type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJtable);

        manageOrganizationJTabbedPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 850, 90));

        addOrganizationJPanel.setBackground(new java.awt.Color(204, 204, 204));
        addOrganizationJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addOrganizationJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addOrganizationJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 25, 330, 10));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Add Organization");
        addOrganizationJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 30));

        organizationName_Jtext.setForeground(new java.awt.Color(204, 204, 204));
        organizationName_Jtext.setText("Organization name:");
        organizationName_Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                organizationName_JtextFocusGained(evt);
            }
        });
        addOrganizationJPanel.add(organizationName_Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 30));

        organizationComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        organizationComboBox.setForeground(new java.awt.Color(204, 204, 204));
        organizationComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                organizationComboBoxFocusGained(evt);
            }
        });
        organizationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationComboBoxActionPerformed(evt);
            }
        });
        addOrganizationJPanel.add(organizationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 30));

        addOrganization_Jbutton.setText("Add Organization");
        addOrganization_Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganization_JbuttonActionPerformed(evt);
            }
        });
        addOrganizationJPanel.add(addOrganization_Jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, -1));

        organizationTypeValidator_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        organizationTypeValidator_Jlabel.setForeground(new java.awt.Color(255, 51, 0));
        addOrganizationJPanel.add(organizationTypeValidator_Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 10));

        organizationNameValidator_Jlabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        organizationNameValidator_Jlabel1.setForeground(new java.awt.Color(255, 0, 0));
        addOrganizationJPanel.add(organizationNameValidator_Jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, 10));

        addOrganizationAdmin_Jbutton.setText("Add organization admin");
        addOrganizationAdmin_Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationAdmin_JbuttonActionPerformed(evt);
            }
        });
        addOrganizationJPanel.add(addOrganizationAdmin_Jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));

        jLabel6.setText("Organization type:");
        addOrganizationJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, -1));

        manageOrganizationJTabbedPanel.add(addOrganizationJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 330, 330));

        manageOrganizationAdminJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        manageOrganizationAdminJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        manageOrganizationAdminJPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 38, 420, 10));

        addOrganizationAdmin_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        addOrganizationAdmin_Jlabel.setText("Manage Organization Admin");
        manageOrganizationAdminJPanel.add(addOrganizationAdmin_Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 153, 25));

        organizationAdminUserName_Jtext.setForeground(new java.awt.Color(204, 204, 204));
        organizationAdminUserName_Jtext.setText("Admin first name:");
        organizationAdminUserName_Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                organizationAdminUserName_JtextFocusGained(evt);
            }
        });
        manageOrganizationAdminJPanel.add(organizationAdminUserName_Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 30));

        organizationAdminEmailId_Jtext.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        organizationAdminEmailId_Jtext.setForeground(new java.awt.Color(204, 204, 204));
        organizationAdminEmailId_Jtext.setText("Admin Email id:");
        organizationAdminEmailId_Jtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                organizationAdminEmailId_JtextFocusGained(evt);
            }
        });
        manageOrganizationAdminJPanel.add(organizationAdminEmailId_Jtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 29));

        addAdmin_Jbutton.setText("Add admin to organization");
        addAdmin_Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdmin_JbuttonActionPerformed(evt);
            }
        });
        manageOrganizationAdminJPanel.add(addAdmin_Jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 260, 30));

        adminNameValidator_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        adminNameValidator_Jlabel.setForeground(new java.awt.Color(255, 51, 0));
        adminNameValidator_Jlabel.setEnabled(false);
        manageOrganizationAdminJPanel.add(adminNameValidator_Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 120, 229, -1));

        adminEmailIdValidator_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        adminEmailIdValidator_Jlabel.setForeground(new java.awt.Color(255, 51, 0));
        adminEmailIdValidator_Jlabel.setEnabled(false);
        manageOrganizationAdminJPanel.add(adminEmailIdValidator_Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 275, 10));

        organizationAdminJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(organizationAdminJtable);

        manageOrganizationAdminJPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 390, 80));

        adminLastNameValidatorJlbl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        adminLastNameValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        manageOrganizationAdminJPanel.add(adminLastNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 200, 10));

        adminLastNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        adminLastNameJtext.setText("Admin last name:");
        adminLastNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminLastNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adminLastNameJtextFocusLost(evt);
            }
        });
        adminLastNameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLastNameJtextActionPerformed(evt);
            }
        });
        manageOrganizationAdminJPanel.add(adminLastNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, 30));

        adminFirstNameValidatorJlbl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        adminFirstNameValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        manageOrganizationAdminJPanel.add(adminFirstNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 10));

        manageOrganizationJTabbedPanel.add(manageOrganizationAdminJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 450, 330));

        manageReportJTabbedPane.addTab("Manage Organization", manageOrganizationJTabbedPanel);

        manageLocalAgentJTabbedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agentDirectoryJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agent user name:", "Transactions", "Registered on"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(agentDirectoryJtable);

        manageLocalAgentJTabbedPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 980, 99));

        viewAgentProfileJbutton.setText("View Agent Profile");
        viewAgentProfileJbutton.setToolTipText("Please select agent to view profile");
        viewAgentProfileJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAgentProfileJbuttonActionPerformed(evt);
            }
        });
        manageLocalAgentJTabbedPanel.add(viewAgentProfileJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 240, 180, 30));

        manageReportJTabbedPane.addTab("Manage Local Agent", manageLocalAgentJTabbedPanel);

        manageExternalEnterpriseJTabbedPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        manageExternalEnterpriseJTabbedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        associatedEnterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Id", "Enterprise Name", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(associatedEnterpriseJTable);

        manageExternalEnterpriseJTabbedPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 670, 140));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Associated Enterprises list:");
        manageExternalEnterpriseJTabbedPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 19, -1, 23));

        manageReportJTabbedPane.addTab("Associated Enterprises", manageExternalEnterpriseJTabbedPanel);

        reportJTabbedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approvedRequestsJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Recipient Name", "Recipient Location", "Senior Staff", "Field Staff", "Requested Date", "Approved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(approvedRequestsJtable);

        reportJTabbedPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 870, 160));

        jButton1.setText("Create user account for recipient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        reportJTabbedPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, 30));

        jButton2.setText("View Enrollment Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        reportJTabbedPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 190, 30));

        manageReportJTabbedPane.addTab("Manage Recipients", reportJTabbedPanel);

        add(manageReportJTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1050, 610));

        enterpriseAdminNameJlbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        add(enterpriseAdminNameJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setName("enterpriseAdminName_Jlabel"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        enterpriseAdminName_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        add(enterpriseAdminName_Jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        jLayeredPane2.setBackground(new java.awt.Color(51, 153, 255));
        jLayeredPane2.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eradicate Poverty");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Share happiness");

        enterpriseName_Jlabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        enterpriseName_Jlabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel5)))
                .addGap(136, 136, 136)
                .addComponent(enterpriseName_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseName_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(enterpriseName_Jlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        enterpriseName_Jlabel.getAccessibleContext().setAccessibleName("enterpriseName_Jlabel");

        add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        welcomeAdminJlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        welcomeAdminJlbl.setText("jLabel6");
        add(welcomeAdminJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

//    
//    public void populateVillageComboBox()
//    {
//        for (Enterprise e:donationEnterprise.getAssociatedEnterprise())
//        {
//            if(e instanceof Government)
//            {
//                government = (Government)e;
//                for(Region region:government.getRegionDirectory().getRegionList())
//                {
//                    for(Village village:region.getVillageList())
//                    {
//                        villageComboBox.addItem(village);
//                    }
//                }
//            }
//        }
//    }
    
    public void populateOrganizationTable(Enterprise enterprise)
    {
        DefaultTableModel dtm = (DefaultTableModel)organizationJtable.getModel();
        dtm.setRowCount(0);
        
        
        for (Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            Object row[]=new Object[3];
            row[0]=organization.getOrganizationID();
            row[1]=organization;
            row[2]=organization.getOrganizationType();
            
            dtm.addRow(row);
        }
    }
    
    public void populateOrganizationAdminTable(Organization organization)
    {
        DefaultTableModel dtm = (DefaultTableModel)organizationAdminJtable.getModel();
        dtm.setRowCount(0);
        
        if(organization.getOrganizationType().equals(Organization.Type.ENROLLMENT))
        {
        for (UserAccount userAccount:organization.getUserAccountDirectory().getUserAccountList())
        {
            if(userAccount.getRole().getRoleype().equals(Role.RoleType.ORGANIZATIONADMIN))
            {
            Object row[]=new Object[2];
            row[0]=userAccount;
            row[1]=userAccount.isIsActive()?"Active":"Disabled";
            
            
            dtm.addRow(row);
            }
            }
        }
        
        
        else if(organization.getOrganizationType().equals(Organization.Type.ACCOUNTS))
        {
        for (UserAccount userAccount:organization.getUserAccountDirectory().getUserAccountList())
        {
            if(userAccount.getRole().getRoleype().equals(Role.RoleType.ACCOUNT_MANAGER))
            {
            Object row[]=new Object[2];
            row[0]=userAccount;
            row[1]=userAccount.isIsActive()?"Active":"Disabled";
            
            
            dtm.addRow(row);
            }
            }
        }
        
    }
    
    public void populateOrganizationComboBox()
    {
        for(Type type:Organization.Type.values())
        {
            organizationComboBox.addItem(type);
        }
    }
    
    
    public void populateApprovedEnrollmentRequestTable()
    {
        
        EnrollmentWorkRequest enrollmentRequest=null;
        DefaultTableModel dtm = (DefaultTableModel)approvedRequestsJtable.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(organization instanceof EnrollmentOrganization)
            {
                for(WorkRequest workRequest:organization.getWorkQueue().getWorkRequestList())
                {
                    if(workRequest instanceof EnrollmentWorkRequest && workRequest.getStatus().equalsIgnoreCase("Approved"))
                    {
                        enrollmentRequest = (EnrollmentWorkRequest)workRequest;
                        Object row[]=new Object[7];
                        row[0]=workRequest;
                        row[1]=enrollmentRequest.getHeadFirstName()+","+enrollmentRequest.getHeadLastName();
                        row[2]=enrollmentRequest.getDistrictName()+"-"+enrollmentRequest.getHeadLastName();
                        row[3]=enrollmentRequest.getUserIdSeniorStaff().getUsername();
                        row[4]=enrollmentRequest.getUserIdFieldStaff().getUsername();
                        row[5]=enrollmentRequest.getRequestDate();
                        row[6]=enrollmentRequest.getResolveDate();
                        dtm.addRow(row);
                    }
                }
            }
        }
        
    }
    private void organizationName_JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_organizationName_JtextFocusGained
                // TODO add your handling code here:
        
        organizationName_Jtext.setText(" ");
        organizationName_Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_organizationName_JtextFocusGained

    private void organizationComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_organizationComboBoxFocusGained
        // TODO add your handling code here:
        populateOrganizationComboBox();
        //organizationComboBox.removeItem(ORGANIZATION);
        organizationComboBox.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_organizationComboBoxFocusGained

    private void addOrganization_JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganization_JbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        organizationNameValidator_Jlabel1.setText("");
        organizationTypeValidator_Jlabel.setText(" ");
        if(!Validation.validateTextFieldsForNonEmpty(organizationName_Jtext)||organizationName_Jtext.getText().equalsIgnoreCase("Organization name:"))
        {
            errorFlag=true;
            organizationNameValidator_Jlabel1.setText("Please enter organization name");
        }
        
         if (!Validation.validateTextFieldsForString(organizationName_Jtext))
        {
            errorFlag=true;
            organizationNameValidator_Jlabel1.setText("Only alphabets and -sign allowed for organization name");
        }
        
        if (String.valueOf(organizationComboBox.getSelectedItem()).equalsIgnoreCase("Please select organization type"))
        {
            errorFlag=true;
            organizationTypeValidator_Jlabel.setText("Please select an organization type");
        }
        
        if(!errorFlag)
        {
            Type type = (Type)organizationComboBox.getSelectedItem();
            //Organization organization = enterprise.getOrganizationDirectory().createOrganization(organizationName_Jtext.getText(),organizationType);
            
            Organization organization = enterprise.getOrganizationDirectory().createOrganization(organizationName_Jtext.getText(),type);
            
            
            
            
            
            populateOrganizationTable(enterprise);
        }
    }//GEN-LAST:event_addOrganization_JbuttonActionPerformed

    private void organizationAdminUserName_JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_organizationAdminUserName_JtextFocusGained
        // TODO add your handling code here:
        organizationAdminUserName_Jtext.setText("");
        organizationAdminUserName_Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_organizationAdminUserName_JtextFocusGained

    private void organizationAdminEmailId_JtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_organizationAdminEmailId_JtextFocusGained
        // TODO add your handling code here:
        organizationAdminEmailId_Jtext.setText("");
        organizationAdminEmailId_Jtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_organizationAdminEmailId_JtextFocusGained

    private void addAdmin_JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdmin_JbuttonActionPerformed
        // TODO add your handling code here:
        
        boolean errorFlag=false;
        adminEmailIdValidator_Jlabel.setText("");
        adminFirstNameValidatorJlbl.setText("");
        adminLastNameValidatorJlbl.setText("");
        adminEmailIdValidator_Jlabel.setForeground(Color.red);
        adminFirstNameValidatorJlbl.setForeground(Color.red);
        adminLastNameValidatorJlbl.setForeground(Color.red);
        int selectedRow = organizationJtable.getSelectedRow();
        
        if (selectedRow>=0)
        {
        Organization organization = (Organization)organizationJtable.getValueAt(selectedRow,1);
        if(!Validation.validateTextFieldsForNonEmpty(organizationAdminUserName_Jtext)||organizationAdminUserName_Jtext.getText().equalsIgnoreCase("Admin first name:"))
        {
            errorFlag=true;
            adminLastNameValidatorJlbl.setEnabled(true);
            adminLastNameValidatorJlbl.setText("Please enter admin first name");
        }
        
         if(!Validation.validateTextFieldsForString(organizationAdminUserName_Jtext))
        {
            errorFlag=true;
            adminFirstNameValidatorJlbl.setEnabled(true);
            adminFirstNameValidatorJlbl.setText("Please enter valid first name");
        }
         
         if(!Validation.validateTextFieldsForString(adminLastNameJtext))
        {
            errorFlag=true;
            adminLastNameValidatorJlbl.setEnabled(true);
            adminLastNameValidatorJlbl.setText("Please enter valid last name");
        }
        
        
        if (!Validation.validateTextFieldsForNonEmpty(organizationAdminEmailId_Jtext)||organizationAdminEmailId_Jtext.getText().equalsIgnoreCase("Admin Email id:"))
        {
            errorFlag=true;
            adminEmailIdValidator_Jlabel.setEnabled(true);
            adminEmailIdValidator_Jlabel.setText("Please enter admin email id");
        }
        
       if (!Validation.validateTextFieldsForEmailId(organizationAdminEmailId_Jtext))
        {
            errorFlag=true;
            adminEmailIdValidator_Jlabel.setEnabled(true);
            adminEmailIdValidator_Jlabel.setText("Please enter valid email id");
        }
        
        if (!errorFlag)
            {
                
                if(!enterprise.getOrganizationDirectory().checkifUserNameisPresent(organizationAdminEmailId_Jtext.getText().trim()))
                {
                Organization.Type selectedOrganizationType = (Organization.Type)organizationComboBox.getSelectedItem();
                UserAccount ua;
                
                Employee employee = organization.getEmployeeDirectory().createEmployee(organizationAdminEmailId_Jtext.getText());
                if(selectedOrganizationType.equals(Organization.Type.ACCOUNTS)){
                    ua = organization.getUserAccountDirectory().createUserAccount(organizationAdminEmailId_Jtext.getText().trim(),"org", employee,new AccountsManagerRole());
                    SendEmail.SendEmail(organizationAdminEmailId_Jtext.getText().trim(),"Welcome to Eradicate Poverty",organizationAdminEmailId_Jtext.getText().trim(),"org");
                }
                else if(selectedOrganizationType.equals(Organization.Type.ENROLLMENT))
                {
                    
                    ua = organization.getUserAccountDirectory().createUserAccount(organizationAdminEmailId_Jtext.getText().trim(),"org", employee,new OrganizationAdminRole());
                    SendEmail.SendEmail(organizationAdminEmailId_Jtext.getText().trim(),"Welcome to Eradicate Poverty",organizationAdminEmailId_Jtext.getText().trim(),"org");
                }
                JOptionPane.showMessageDialog(null,"New organization admin is created successfully","User account created",JOptionPane.INFORMATION_MESSAGE);
                populateOrganizationAdminTable(organization);
                
                
                organizationAdminUserName_Jtext.setText("");
                organizationAdminEmailId_Jtext.setText("");
            }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"User account with email id"+organizationAdminEmailId_Jtext.getText().trim()+" already exists","Duplicate entry",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        
        
        
    }
        
        else
            
        {
            JOptionPane.showMessageDialog(null,"Please select organization admin to add admin","No selection",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_addAdmin_JbuttonActionPerformed

    private void addOrganizationAdmin_JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationAdmin_JbuttonActionPerformed
        // TODO add your handling code here:
         int selectedRow = organizationJtable.getSelectedRow();
         
         if(selectedRow>=0)
         {
             Organization organization = (Organization)organizationJtable.getValueAt(selectedRow,1);
             manageOrganizationAdminJPanel.setVisible(true);
             populateOrganizationAdminTable(organization);
         }
         
         else
         {
             JOptionPane.showMessageDialog(null,"Please select organization to add admin","No selection",JOptionPane.ERROR_MESSAGE);
             return;
         }
        
    }//GEN-LAST:event_addOrganizationAdmin_JbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Recipient recipient=null;
        int selectedRow = approvedRequestsJtable.getSelectedRow();
        EnrollmentWorkRequest enrollmentWorkRequest=null;
        if(selectedRow>=0)
        {
            WorkRequest workRequest = (WorkRequest)approvedRequestsJtable.getValueAt(selectedRow,0);    
        if(workRequest instanceof EnrollmentWorkRequest)
        enrollmentWorkRequest = (EnrollmentWorkRequest)workRequest;
        Village village =enrollmentWorkRequest.getVillageName();
        
           recipient = village.addRecipient(enrollmentWorkRequest.getDailyIncome());
           enterprise.getPersonDirectory().addPerson(recipient);
           UserAccount recipientUserAccount = enterprise.getUserAccountDirectory().createUserAccount(String.valueOf(enrollmentWorkRequest.getCellPhoneNo()),"1234",recipient, new RecipientRole());
           
           recipient.setMpin("123");
           recipient.setStartKey("EP");
           recipient.getProfile().setHeadFirstName(enrollmentWorkRequest.getHeadFirstName());
           recipient.getProfile().setHeadLastName(enrollmentWorkRequest.getHeadLastName());
           recipient.getProfile().setHeadMiddleName(enrollmentWorkRequest.getHeadMiddleName());
           recipient.getProfile().setHeadGender(enrollmentWorkRequest.getHeadGender());
           recipient.getProfile().setHeadMaritalStatus(enrollmentWorkRequest.getHeadMaritalStatus());
           recipient.getProfile().setEducationStatus(enrollmentWorkRequest.getEducationStatus());
           recipient.getProfile().setSchoolName(enrollmentWorkRequest.getSchoolName());
           recipient.getProfile().setSchoolDetails(enrollmentWorkRequest.getSchoolDetails());
           recipient.getProfile().setEmploymentStatus(enrollmentWorkRequest.getEmploymentStatus());
           recipient.getProfile().setEmployerName(enrollmentWorkRequest.getEmployerName());
           recipient.getProfile().setEmployerDetails(enrollmentWorkRequest.getEmployerDetails());
           recipient.getProfile().setDailyIncome(enrollmentWorkRequest.getDailyIncome());
           recipient.getProfile().setSpouseName(enrollmentWorkRequest.getSpouseName());
           recipient.setNoOfMemebers(enrollmentWorkRequest.getNoOfMembers());
           recipient.setNoOfAdults(enrollmentWorkRequest.getNoOfAdults());
           recipient.setNoOfChildren(enrollmentWorkRequest.getNoOfChildren());
           recipient.getLocation().setDistrictName(enrollmentWorkRequest.getDistrictName());
           recipient.getLocation().setVillageName(enrollmentWorkRequest.getVillageName());
           recipient.getLocation().setHomeImage(enrollmentWorkRequest.getHomeImagePath());
           recipient.setUserAccount(recipientUserAccount);
           for(LocalAgent localAgent:village.getLocalAgent())
           {
               recipient.getAssignedLocalAgent().add(localAgent);
           }
           
           try
           {
           recipient.getProfile().setCellPhoneNo(Integer.parseInt(enrollmentWorkRequest.getCellPhoneNo()));
           }
           
           catch(Exception e){}
           
           
           
           
           JOptionPane.showMessageDialog(null,"New Recipient "+enrollmentWorkRequest.getCellPhoneNo()+" is created successfully.\n Start pin will be texted shortly to recipient.","New member added",JOptionPane.INFORMATION_MESSAGE);
           
           
           
           
           
           
            
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select enrollment request to create recipient account","No selection",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        int selectedRow = approvedRequestsJtable.getSelectedRow();
        EnrollmentWorkRequest enrollmentWorkRequest=null;
        if(selectedRow>=0)
        {
            WorkRequest workRequest = (WorkRequest)approvedRequestsJtable.getValueAt(selectedRow,0);    
        if(workRequest instanceof EnrollmentWorkRequest)
        enrollmentWorkRequest = (EnrollmentWorkRequest)workRequest;
        
        ProcessEnrollmentRequestJpanel processEnrollmentRequestJpanel=new ProcessEnrollmentRequestJpanel(userProcessContainer,enrollmentWorkRequest,userAccount);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("processEnrollmentRequestJpanel",processEnrollmentRequestJpanel);
                layout.next(userProcessContainer);
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(null,"Please select registration request from requests table","No selection",JOptionPane.ERROR_MESSAGE);
        }
        
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adminLastNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminLastNameJtextFocusGained
        // TODO add your handling code here:

        
            adminLastNameJtext.setText("");
            adminLastNameJtext.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_adminLastNameJtextFocusGained

    private void adminLastNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminLastNameJtextFocusLost
        // TODO add your handling code here:

        if(adminLastNameJtext.getText().equalsIgnoreCase(""))
        {
            adminLastNameJtext.setText("Admin last name:");
            adminLastNameJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_adminLastNameJtextFocusLost

    private void adminLastNameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLastNameJtextActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_adminLastNameJtextActionPerformed

    
    public void populateLocalAgentTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)agentDirectoryJtable.getModel();
        dtm.setRowCount(0);
        
        Date date = new Date();
        MobileEnterprise mobileEnterprise;
       for(Enterprise e:donationEnterprise.getAssociatedEnterprise())
       {
           if(e instanceof MobileEnterprise)
           {
              mobileEnterprise = (MobileEnterprise)e;
              for(LocalAgent localAgent:mobileEnterprise.getLocalAgentDirectory().getLocalAgentList())
              {
                  
                      Object row[]=new Object[3];
                      row[0]=localAgent;
                      row[1]=localAgent.getAgentTransactionsList().getTransactionList().size();
                      row[2]=localAgent.getAgentVillage();
                      dtm.addRow(row);
                 
              }
           }
       }
    }
    private void viewAgentProfileJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAgentProfileJbuttonActionPerformed
        // TODO add your handling code here:
        
        if(Validation.validateTableSelection(agentDirectoryJtable,1))
        {
            int selectedRow = agentDirectoryJtable.getSelectedRow();
            LocalAgent localAgent =(LocalAgent) agentDirectoryJtable.getValueAt(selectedRow,0);
            
            
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(null,"Please select Local agent to view profile");
            return;
        }
    }//GEN-LAST:event_viewAgentProfileJbuttonActionPerformed

    private void organizationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationComboBoxActionPerformed

    
//    public void populateEnterpriseTypeComboBox()
//    {
//        for (Enterprise.EnterpriseType type:Enterprise.EnterpriseType.values())
//        {
//            if(!type.equals(Enterprise.EnterpriseType.DONATION))
//            {
//                enterpriseTypeComboBox.addItem(type);
//            }
//        }
//    }
    
//    public boolean validateAddEnterpriseForm()
//    {
//        boolean errorFlag=false;
//        enterpriseNameValidatorJlabel.setText("");
//        enterpriseTypeValidatorJlabel.setText("");
//        
//        if(!Validation.validateTextFieldsForNonEmpty(enterpriseName_Jtext)||enterpriseName_Jtext.getText().trim().equalsIgnoreCase("Enterprise name:"))
//        {
//            errorFlag=true;
//            enterpriseNameValidatorJlabel.setText("Please enter enterprise name");
//        }
//        
//        if(String.valueOf(enterpriseTypeComboBox.getSelectedItem()).equalsIgnoreCase("Please select enterprise type"))
//        {
//            errorFlag=true;
//            enterpriseTypeValidatorJlabel.setText("Please select enterprise typw");
//        }
//        
//        return errorFlag;
//        
//        
//       
//    }
//    
    
    public void populateAssociatedEnterprise()
    {
        
         DefaultTableModel dtm = (DefaultTableModel)associatedEnterpriseJTable.getModel();
        dtm.setRowCount(0);
        
        DonationEnterprise donationEnterprise = null;
        if(enterprise instanceof DonationEnterprise)
            donationEnterprise = (DonationEnterprise)enterprise;
        
        for (Enterprise e:donationEnterprise.getAssociatedEnterprise())
        {
            Object row[]=new Object[3];
            row[0]=e.getEnterpriseId();
            row[1]=e;
            row[2]=e.getEnterpriseType();
            
            
            dtm.addRow(row);
        }
        
        
    }
    
//    public boolean validateEnterpriseAdminFormFields()
//    {
//        boolean errorFlag=false;
//        
//        if (!Validation.validateTextFieldsForNonEmpty(enterpriseAdminfirstName_Jtext)||enterpriseAdminfirstName_Jtext.getText().trim().equalsIgnoreCase("First name:"))
//                {
//                    errorFlag=true;
//                    enterpriseAdminFirstNameValidatorJlabel.setVisible(true);
//                    enterpriseAdminFirstNameValidatorJlabel.setText("Please enter first name:");
//                    
//                }
//        
//        if (Validation.validateTextFieldsForNonEmpty(enterpriseAdminlastName_Jtext)||enterpriseAdminlastName_Jtext.getText().trim().equalsIgnoreCase("Last name:"))
//        {
//                errorFlag=true;
//                enterpriseAdminLastNameValidatorJlabel.setVisible(true);
//                enterpriseAdminLastNameValidatorJlabel.setText("Please enter last name:");
//            
//        }
//        
//        return errorFlag;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin_Jbutton;
    private javax.swing.JButton addOrganizationAdmin_Jbutton;
    private javax.swing.JLabel addOrganizationAdmin_Jlabel;
    private javax.swing.JLayeredPane addOrganizationJPanel;
    private javax.swing.JButton addOrganization_Jbutton;
    private javax.swing.JLabel adminEmailIdValidator_Jlabel;
    private javax.swing.JLabel adminFirstNameValidatorJlbl;
    private javax.swing.JTextField adminLastNameJtext;
    private javax.swing.JLabel adminLastNameValidatorJlbl;
    private javax.swing.JLabel adminNameValidator_Jlabel;
    private javax.swing.JTable agentDirectoryJtable;
    private javax.swing.JTable approvedRequestsJtable;
    private javax.swing.JTable associatedEnterpriseJTable;
    private javax.swing.JLabel enterpriseAdminNameJlbl;
    private javax.swing.JLabel enterpriseAdminName_Jlabel;
    private javax.swing.JLabel enterpriseName_Jlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel manageExternalEnterpriseJTabbedPanel;
    private javax.swing.JPanel manageLocalAgentJTabbedPanel;
    private javax.swing.JLayeredPane manageOrganizationAdminJPanel;
    private javax.swing.JPanel manageOrganizationJTabbedPanel;
    private javax.swing.JTabbedPane manageReportJTabbedPane;
    private javax.swing.JTextField organizationAdminEmailId_Jtext;
    private javax.swing.JTable organizationAdminJtable;
    private javax.swing.JTextField organizationAdminUserName_Jtext;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTable organizationJtable;
    private javax.swing.JLabel organizationNameValidator_Jlabel1;
    private javax.swing.JTextField organizationName_Jtext;
    private javax.swing.JLabel organizationTypeValidator_Jlabel;
    private javax.swing.JPanel reportJTabbedPanel;
    private javax.swing.JButton viewAgentProfileJbutton;
    private javax.swing.JLabel welcomeAdminJlbl;
    // End of variables declaration//GEN-END:variables
}
