/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Donor;

import Business.Payment.Payment;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJPL
 */
public class DonorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Payment payment;
    public DonorWorkAreaJPanel(JPanel upc,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount=userAccount;
        welcomeJlbl.setText("Welcome "+userAccount.getUsername());
        populatePaymentHistory();
    }
    
    public void populatePaymentHistory()
    {
        DefaultTableModel dtm = (DefaultTableModel)paymentHistoryJtable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest workRequest:userAccount.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof Payment)
            {
                payment = (Payment)workRequest;
                Object row[]= new Object[4];
                row[0]=payment;
                row[1]=payment.getAmount();
                row[2]=payment.getRegion();
                row[3]=payment.getReceiver();
                dtm.addRow(row);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcomeJlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentHistoryJtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        donationRequestDetailsJPanel = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        requestNoJlbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amountJtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        regionNameJtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        responsibleJtxt = new javax.swing.JTextField();
        amountJtext1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(51, 153, 255));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eradicate Poverty");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Share happiness");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)))
                .addContainerGap(834, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1080, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1040, -1));

        welcomeJlbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 380, 40));

        paymentHistoryJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment Id", "Donation Amount", "Status", "Currently Responsible", "Payment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paymentHistoryJtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 220, 1000, 90));

        jButton1.setText("Select a donation to view details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 360, 220, 40));

        donationRequestDetailsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        donationRequestDetailsJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Donation Request no:");
        donationRequestDetailsJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 13, -1, 20));
        donationRequestDetailsJPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, -1));
        donationRequestDetailsJPanel.add(requestNoJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 4, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Donation amount:");
        donationRequestDetailsJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        amountJtext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountJtext.setEnabled(false);
        donationRequestDetailsJPanel.add(amountJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Region:");
        donationRequestDetailsJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, 20));

        regionNameJtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        regionNameJtxt.setEnabled(false);
        donationRequestDetailsJPanel.add(regionNameJtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Currently responsible:");
        donationRequestDetailsJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, 20));

        responsibleJtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        responsibleJtxt.setEnabled(false);
        donationRequestDetailsJPanel.add(responsibleJtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 140, 30));

        amountJtext1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountJtext1.setEnabled(false);
        donationRequestDetailsJPanel.add(amountJtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Payment Mode:");
        donationRequestDetailsJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jPanel1.add(donationRequestDetailsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 1000, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = paymentHistoryJtable.getSelectedRow();
        
        if(selectedRow>=0)
        {
         
            donationRequestDetailsJPanel.setVisible(true);
            Payment selectedPayment =(Payment) paymentHistoryJtable.getValueAt(selectedRow,0);
            amountJtext.setText(String.valueOf(payment.getAmount()));
            regionNameJtxt.setText(String.valueOf(payment.getRegion()));
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a donation to view details","No selection",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountJtext;
    private javax.swing.JTextField amountJtext1;
    private javax.swing.JLayeredPane donationRequestDetailsJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable paymentHistoryJtable;
    private javax.swing.JTextField regionNameJtxt;
    private javax.swing.JLabel requestNoJlbl;
    private javax.swing.JTextField responsibleJtxt;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
