/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.MobileEnterprise;

import Business.Bank.SavingsAccount;
import Business.Enterprise.Enterprise;
import Business.GovernmentEnterprise.Region;
import Business.LocalAgent.LocalAgent;
import Business.MobileEnterprise.MobileEnterprise;
import Business.Role.LocalAgentRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AgentRegistrationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJPL
 */
public class MobileEnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MobileEnterpriseAdminWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private MobileEnterprise mobileEnterprise;
    private UserAccount userAccount;
    private BufferedImage bufferedImg=null;
    
    public MobileEnterpriseAdminWorkAreaJPanel(JPanel upc,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        if (enterprise instanceof MobileEnterprise)
            this.mobileEnterprise = (MobileEnterprise)enterprise;
        this.userAccount=userAccount;
        hideJPanels();
        populateRequestTable();
                
    }
    
    public void hideJPanels()
    {
        processRequestJPanel.setVisible(false);
        
    }

    
    public void populateRequestTable()
    {
        
        DefaultTableModel dtm = (DefaultTableModel)requestJtable.getModel();
        dtm.setRowCount(0);
        
                for(WorkRequest workRequest:mobileEnterprise.getWorkQueue().getWorkRequestList())
                {
                    if(workRequest instanceof AgentRegistrationWorkRequest && workRequest.getStatus().equalsIgnoreCase("Requested"))
                    {
                        AgentRegistrationWorkRequest agentWorkRequest = (AgentRegistrationWorkRequest)workRequest;
                        Object row[]=new Object[4];
                        row[0]=workRequest.getRequestDate();
                        row[1]=agentWorkRequest;
                        row[2]=agentWorkRequest.getEmailAddress();
                        row[3]=agentWorkRequest.getAgentRegion()+" - "+agentWorkRequest.getAgentVillage();
                        dtm.addRow(row);
                    }
                    
                }
                
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        manageRegistrationRequestJPanel = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJtable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        processRequestJPanel = new javax.swing.JLayeredPane();
        jSeparator3 = new javax.swing.JSeparator();
        requestDetailJlbl = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        yearEstablishmentJtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        outletTypeJtext1 = new javax.swing.JTextField();
        outletNameJtext2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        adminInfoJPanel = new javax.swing.JLayeredPane();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lastNameJtext = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        villageJtext = new javax.swing.JTextField();
        villageValidatorJlbl = new javax.swing.JLabel();
        stateJtext = new javax.swing.JTextField();
        agentFirstNameJtext = new javax.swing.JTextField();
        idTypeJtext = new javax.swing.JTextField();
        emailAddressJtext = new javax.swing.JTextField();
        idNumberJtext1 = new javax.swing.JTextField();
        showCertificateJPanel = new javax.swing.JLayeredPane();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        certificateImageJlbl = new javax.swing.JLabel();
        decisionJPanel = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        ApprovedJRadioButton = new javax.swing.JRadioButton();
        decisionJRadioButton = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTextJtextArea = new javax.swing.JTextArea();
        processJbutton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("M-PESA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, -1));

        manageRegistrationRequestJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        manageRegistrationRequestJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Requester Name", "Requester Email Address", "Requester Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestJtable);

        manageRegistrationRequestJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 860, 90));
        manageRegistrationRequestJPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Manage Registration Requests");
        manageRegistrationRequestJPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jButton4.setText("Check & Process Request");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        manageRegistrationRequestJPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, 30));

        add(manageRegistrationRequestJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 900, 220));

        processRequestJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        processRequestJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        processRequestJPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, -1));

        requestDetailJlbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        processRequestJPanel.add(requestDetailJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 530, 20));

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 600, -1));

        jLabel3.setText(">>  Year of establishment:");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 30));

        yearEstablishmentJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        yearEstablishmentJtext.setForeground(new java.awt.Color(204, 204, 204));
        yearEstablishmentJtext.setEnabled(false);
        yearEstablishmentJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearEstablishmentJtextFocusGained(evt);
            }
        });
        jLayeredPane1.add(yearEstablishmentJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, 30));

        jLabel5.setText(">>   Name of outlet:");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, 30));

        jLabel6.setText(">>   Type of outlet:");
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, 30));

        outletTypeJtext1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        outletTypeJtext1.setForeground(new java.awt.Color(204, 204, 204));
        outletTypeJtext1.setEnabled(false);
        outletTypeJtext1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                outletTypeJtext1FocusGained(evt);
            }
        });
        jLayeredPane1.add(outletTypeJtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 30));

        outletNameJtext2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        outletNameJtext2.setForeground(new java.awt.Color(204, 204, 204));
        outletNameJtext2.setEnabled(false);
        outletNameJtext2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                outletNameJtext2FocusGained(evt);
            }
        });
        jLayeredPane1.add(outletNameJtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Outlet Information");
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        processRequestJPanel.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 230));

        adminInfoJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        adminInfoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        adminInfoJPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 27, 1016, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Admininstrator Information");
        adminInfoJPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 6, -1, -1));

        jLabel12.setText(">> Select Village:");
        adminInfoJPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 30));

        lastNameJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        lastNameJtext.setEnabled(false);
        lastNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameJtextFocusGained(evt);
            }
        });
        lastNameJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJtextActionPerformed(evt);
            }
        });
        adminInfoJPanel.add(lastNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 158, 32));

        jLabel15.setText(">>  Last Name:");
        adminInfoJPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, 30));

        jLabel16.setText(">>  Id type:");
        adminInfoJPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel17.setText(">> Email address:");
        adminInfoJPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 30));

        jLabel18.setText(">>  First Name:");
        adminInfoJPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 30));

        jLabel20.setText(">> Select state:");
        adminInfoJPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 30));

        jLabel21.setText(">> Id number:");
        adminInfoJPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 30));

        villageJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        villageJtext.setForeground(new java.awt.Color(204, 204, 204));
        villageJtext.setEnabled(false);
        villageJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                villageJtextFocusGained(evt);
            }
        });
        villageJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villageJtextActionPerformed(evt);
            }
        });
        adminInfoJPanel.add(villageJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 140, 33));

        villageValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        villageValidatorJlbl.setText("jLabel8");
        adminInfoJPanel.add(villageValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 300, 20));

        stateJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        stateJtext.setForeground(new java.awt.Color(204, 204, 204));
        stateJtext.setEnabled(false);
        stateJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateJtextFocusGained(evt);
            }
        });
        adminInfoJPanel.add(stateJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 30));

        agentFirstNameJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agentFirstNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        agentFirstNameJtext.setEnabled(false);
        agentFirstNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                agentFirstNameJtextFocusGained(evt);
            }
        });
        adminInfoJPanel.add(agentFirstNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 160, 30));

        idTypeJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idTypeJtext.setForeground(new java.awt.Color(204, 204, 204));
        idTypeJtext.setEnabled(false);
        idTypeJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTypeJtextFocusGained(evt);
            }
        });
        adminInfoJPanel.add(idTypeJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 30));

        emailAddressJtext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        emailAddressJtext.setForeground(new java.awt.Color(204, 204, 204));
        emailAddressJtext.setEnabled(false);
        emailAddressJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailAddressJtextFocusGained(evt);
            }
        });
        adminInfoJPanel.add(emailAddressJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 30));

        idNumberJtext1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idNumberJtext1.setForeground(new java.awt.Color(204, 204, 204));
        idNumberJtext1.setEnabled(false);
        idNumberJtext1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idNumberJtext1FocusGained(evt);
            }
        });
        idNumberJtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberJtext1ActionPerformed(evt);
            }
        });
        adminInfoJPanel.add(idNumberJtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 158, 33));

        processRequestJPanel.add(adminInfoJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 540, 230));

        showCertificateJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ownership Certificate");

        javax.swing.GroupLayout showCertificateJPanelLayout = new javax.swing.GroupLayout(showCertificateJPanel);
        showCertificateJPanel.setLayout(showCertificateJPanelLayout);
        showCertificateJPanelLayout.setHorizontalGroup(
            showCertificateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(showCertificateJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showCertificateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(certificateImageJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(showCertificateJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
        );
        showCertificateJPanelLayout.setVerticalGroup(
            showCertificateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showCertificateJPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(certificateImageJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        showCertificateJPanel.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        showCertificateJPanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        showCertificateJPanel.setLayer(certificateImageJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        processRequestJPanel.add(showCertificateJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 320, 200));

        decisionJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        decisionJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Process Request");
        decisionJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 2, -1, -1));
        decisionJPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 25, 420, 10));

        ApprovedJRadioButton.setSelected(true);
        ApprovedJRadioButton.setText("Approve");
        decisionJPanel.add(ApprovedJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        decisionJRadioButton.setText("Reject");
        decisionJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisionJRadioButtonActionPerformed(evt);
            }
        });
        decisionJPanel.add(decisionJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Message:");
        decisionJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("*");
        decisionJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 10, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Decision:");
        decisionJPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        requestTextJtextArea.setColumns(20);
        requestTextJtextArea.setRows(5);
        jScrollPane2.setViewportView(requestTextJtextArea);

        decisionJPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 50));

        processJbutton.setText("Process");
        processJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJbuttonActionPerformed(evt);
            }
        });
        decisionJPanel.add(processJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 110, 30));

        processRequestJPanel.add(decisionJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 420, 190));

        add(processRequestJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 900, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void yearEstablishmentJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearEstablishmentJtextFocusGained
        // TODO add your handling code here:

        yearEstablishmentJtext.setText("");
        yearEstablishmentJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_yearEstablishmentJtextFocusGained

    private void stateJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJtextFocusGained

    private void outletTypeJtext1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outletTypeJtext1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_outletTypeJtext1FocusGained

    private void lastNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJtextFocusGained
        // TODO add your handling code here:

        lastNameJtext.setText("");
        lastNameJtext.setForeground(Color.black);
    }//GEN-LAST:event_lastNameJtextFocusGained

    private void lastNameJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJtextActionPerformed

    private void villageJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_villageJtextFocusGained
        // TODO add your handling code here:

        villageJtext.setText("");
        villageJtext.setForeground(Color.black);
    }//GEN-LAST:event_villageJtextFocusGained

    private void villageJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villageJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villageJtextActionPerformed

    private void outletNameJtext2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outletNameJtext2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_outletNameJtext2FocusGained

    private void agentFirstNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_agentFirstNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_agentFirstNameJtextFocusGained

    private void idTypeJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTypeJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idTypeJtextFocusGained

    private void emailAddressJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailAddressJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddressJtextFocusGained

    private void idNumberJtext1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNumberJtext1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberJtext1FocusGained

    private void idNumberJtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberJtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberJtext1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = requestJtable.getSelectedRow();
        
        if (selectedRow>=0)
        {
        AgentRegistrationWorkRequest agentWorkRequest = (AgentRegistrationWorkRequest)requestJtable.getValueAt(selectedRow,1);
        processRequestJPanel.setVisible(true);
        requestDetailJlbl.setText("New request from "+agentWorkRequest);
        
        outletNameJtext2.setText(agentWorkRequest.getOutletName());
        outletTypeJtext1.setText(agentWorkRequest.getOutletType());
        yearEstablishmentJtext.setText(agentWorkRequest.getYearEstablishment());
        agentFirstNameJtext.setText(agentWorkRequest.getAgentFirstName());
        lastNameJtext.setText(agentWorkRequest.getAgentLastName());
        idTypeJtext.setText(agentWorkRequest.getIdType());
        idNumberJtext1.setText(agentWorkRequest.getIdNumber());
        emailAddressJtext.setText(agentWorkRequest.getEmailAddress());
        stateJtext.setText(String.valueOf(agentWorkRequest.getAgentRegion()));
        villageJtext.setText(String.valueOf(agentWorkRequest.getAgentVillage()));
        if(agentWorkRequest.getCertificatePath()!=null){
        ImageIcon imgIco=new ImageIcon(agentWorkRequest.getCertificatePath());
        certificateImageJlbl.setIcon(new ImageIcon(imgIco.getImage().getScaledInstance(212, 122, java.awt.Image.SCALE_FAST)));
        
        }
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select work request to check and process","No selection",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void decisionJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisionJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decisionJRadioButtonActionPerformed

    private void processJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJbuttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestJtable.getSelectedRow();
        AgentRegistrationWorkRequest agentWorkRequest = (AgentRegistrationWorkRequest)requestJtable.getValueAt(selectedRow,1);
        
        
            agentWorkRequest.setStatus("Approved");
            LocalAgent localAgent=mobileEnterprise.getLocalAgentDirectory().addLocalAgent(agentWorkRequest.getEmailAddress());
            
                String userName=agentWorkRequest.getAgentLastName();
                //if(mobileEnterprise.getUserAccountDirectory().checkifUsernameisUnique(userName))
                //{
                    UserAccount userAccount = mobileEnterprise.getUserAccountDirectory().createUserAccount(userName,"local",localAgent,new LocalAgentRole());
                    localAgent.setUserAccount(userAccount);
                    SavingsAccount localAgentSavingsAccount = new SavingsAccount();
                    localAgent.setAgentFirstName(agentFirstNameJtext.getText());
                    localAgent.setAgentLastName(lastNameJtext.getText());
                    localAgent.setOutletName(outletNameJtext2.getText());
                    localAgent.setOutletType(outletTypeJtext1.getText());
                    localAgent.setYearEstablishment(yearEstablishmentJtext.getText());
                    localAgent.setCertificatePath(agentWorkRequest.getCertificatePath());
                    localAgent.setAgentRegion(agentWorkRequest.getAgentRegion());
                    localAgent.setAgentVillage(agentWorkRequest.getAgentVillage());
                    localAgent.setIdNumber(idNumberJtext1.getText());
                    localAgent.setIdType(idTypeJtext.getText());
                    localAgent.setSavingsAccount(localAgentSavingsAccount);
                    
                    agentWorkRequest.getAgentVillage().getLocalAgent().add(localAgent);
                    
                    
                    JOptionPane.showMessageDialog(null,"New local agent is created successfully");
                    processRequestJPanel.setVisible(false);
                    populateRequestTable();
                    
                //}
            
        
        
        
        
    }//GEN-LAST:event_processJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ApprovedJRadioButton;
    private javax.swing.JLayeredPane adminInfoJPanel;
    private javax.swing.JTextField agentFirstNameJtext;
    private javax.swing.JLabel certificateImageJlbl;
    private javax.swing.JLayeredPane decisionJPanel;
    private javax.swing.JRadioButton decisionJRadioButton;
    private javax.swing.JTextField emailAddressJtext;
    private javax.swing.JTextField idNumberJtext1;
    private javax.swing.JTextField idTypeJtext;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lastNameJtext;
    private javax.swing.JLayeredPane manageRegistrationRequestJPanel;
    private javax.swing.JTextField outletNameJtext2;
    private javax.swing.JTextField outletTypeJtext1;
    private javax.swing.JButton processJbutton;
    private javax.swing.JLayeredPane processRequestJPanel;
    private javax.swing.JLabel requestDetailJlbl;
    private javax.swing.JTable requestJtable;
    private javax.swing.JTextArea requestTextJtextArea;
    private javax.swing.JLayeredPane showCertificateJPanel;
    private javax.swing.JTextField stateJtext;
    private javax.swing.JTextField villageJtext;
    private javax.swing.JLabel villageValidatorJlbl;
    private javax.swing.JTextField yearEstablishmentJtext;
    // End of variables declaration//GEN-END:variables
}
