/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.SystemAdmin;

import Business.UserAccount.UserAccount;
import Business.Utility.Validation;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JJPL
 */
public class ManageProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProfileJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public ManageProfileJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        populateFields();
        hideAllLabels();
        detailsJPanel.setEnabled(false);
        
    }
    
    
    public void hideAllLabels()
    {
        passwordValidatorJlbl.setText("");
        passwordStrengthJlbl.setText("");
        firstNameValidatorJlbl.setText("");
        lastNameValidatorJlbl.setText("");
        middleNameValidatorJlbl.setText("");
        monthValidatorJlbl.setText("");
        dateValidatorJlbl.setText("");
        yearValidatorJlbl.setText("");
        idNoValidatorJlbl.setText("");
        primaryContactNoValidatorJlbl.setText("");
        secondaryContactNoValidatorJlbl.setText("");
        addressValidatorJlbl.setText("");
        cityValidatorJlbl.setText("");
        stateValidatorJlbl.setText("");
        zipCodeValidatorJlbl.setText("");
        passwordStrengthValueJlbl.setText("");
    }
    
    public void populateFields()
    {
        emailIdJtext.setText(userAccount.getPerson().getEmailId());
//        roleJtext.setText(String.valueOf(userAccount.getRole().getRoleype().getValue()));
        userNameJtext.setText(userAccount.getUsername());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcomeJlbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        profileDetailsJPanel = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userNameJtext = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailIdJtext = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        roleJtext = new javax.swing.JTextField();
        saveAccountJbutton = new javax.swing.JButton();
        passwordJtext = new javax.swing.JPasswordField();
        passwordValidatorJlbl = new javax.swing.JLabel();
        passwordStrengthJlbl = new javax.swing.JLabel();
        passwordStrengthValueJlbl = new javax.swing.JLabel();
        detailsJPanel = new javax.swing.JLayeredPane();
        secondaryPhoneNoJtext = new javax.swing.JTextField();
        zipcodeJtext = new javax.swing.JTextField();
        lastNameJtext = new javax.swing.JTextField();
        birthMonthComboBox = new javax.swing.JComboBox();
        birthDateComboBox = new javax.swing.JComboBox();
        birthYearComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        idComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        middleNameJtext = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        firstNameJtext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        primaryPhoneNoJtext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idNoJtext = new javax.swing.JTextField();
        cityJtext = new javax.swing.JTextField();
        stateJtext = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        streetJtext = new javax.swing.JTextField();
        firstNameValidatorJlbl = new javax.swing.JLabel();
        middleNameValidatorJlbl = new javax.swing.JLabel();
        lastNameValidatorJlbl = new javax.swing.JLabel();
        dateValidatorJlbl = new javax.swing.JLabel();
        secondaryContactNoValidatorJlbl = new javax.swing.JLabel();
        addressValidatorJlbl = new javax.swing.JLabel();
        yearValidatorJlbl = new javax.swing.JLabel();
        monthValidatorJlbl = new javax.swing.JLabel();
        primaryContactNoValidatorJlbl = new javax.swing.JLabel();
        stateValidatorJlbl = new javax.swing.JLabel();
        idNoValidatorJlbl = new javax.swing.JLabel();
        zipCodeValidatorJlbl = new javax.swing.JLabel();
        cityValidatorJlbl = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(51, 153, 255));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eradicate Poverty");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Share happiness");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)))
                .addContainerGap(854, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        welcomeJlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        welcomeJlbl.setText("jLabel3");
        add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 80, 210, 20));

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 130, -1));

        profileDetailsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Username:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Account Details:");

        userNameJtext.setEditable(false);
        userNameJtext.setEnabled(false);
        userNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameJtextFocusGained(evt);
            }
        });

        jLabel12.setText("Email id:");

        emailIdJtext.setEditable(false);
        emailIdJtext.setEnabled(false);
        emailIdJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIdJtextFocusGained(evt);
            }
        });

        jLabel13.setText("New Password:");

        jLabel14.setText("Role:");

        roleJtext.setEditable(false);
        roleJtext.setEnabled(false);
        roleJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roleJtextFocusGained(evt);
            }
        });

        saveAccountJbutton.setText("SAVE");
        saveAccountJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAccountJbuttonActionPerformed(evt);
            }
        });

        passwordJtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordJtextKeyPressed(evt);
            }
        });

        passwordValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        passwordValidatorJlbl.setText("jLabel15");

        passwordStrengthJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passwordStrengthJlbl.setText("jLabel15");

        passwordStrengthValueJlbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        passwordStrengthValueJlbl.setText("jLabel15");

        javax.swing.GroupLayout profileDetailsJPanelLayout = new javax.swing.GroupLayout(profileDetailsJPanel);
        profileDetailsJPanel.setLayout(profileDetailsJPanelLayout);
        profileDetailsJPanelLayout.setHorizontalGroup(
            profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileDetailsJPanelLayout.createSequentialGroup()
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                        .addComponent(passwordValidatorJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(saveAccountJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                        .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameJtext, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(passwordJtext)
                            .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                                .addComponent(passwordStrengthJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordStrengthValueJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(74, 74, 74)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailIdJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        profileDetailsJPanelLayout.setVerticalGroup(
            profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetailsJPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userNameJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(emailIdJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJtext)
                    .addComponent(roleJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordStrengthJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordStrengthValueJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileDetailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAccountJbutton)
                    .addComponent(passwordValidatorJlbl))
                .addContainerGap())
        );
        profileDetailsJPanel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(userNameJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(emailIdJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(roleJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(saveAccountJbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(passwordJtext, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(passwordValidatorJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(passwordStrengthJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        profileDetailsJPanel.setLayer(passwordStrengthValueJlbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(profileDetailsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 870, 190));

        detailsJPanel.setBackground(new java.awt.Color(204, 204, 204));
        detailsJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        detailsJPanel.setEnabled(false);
        detailsJPanel.setOpaque(true);
        detailsJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondaryPhoneNoJtext.setForeground(new java.awt.Color(204, 204, 204));
        secondaryPhoneNoJtext.setText("Secondary contact no:");
        secondaryPhoneNoJtext.setEnabled(false);
        secondaryPhoneNoJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                secondaryPhoneNoJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                secondaryPhoneNoJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(secondaryPhoneNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 250, 30));

        zipcodeJtext.setForeground(new java.awt.Color(204, 204, 204));
        zipcodeJtext.setText("Zip Code");
        zipcodeJtext.setEnabled(false);
        zipcodeJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipcodeJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipcodeJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(zipcodeJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 110, 30));

        lastNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        lastNameJtext.setText("Last name:");
        lastNameJtext.setEnabled(false);
        lastNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(lastNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 140, 30));

        birthMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        birthMonthComboBox.setEnabled(false);
        detailsJPanel.add(birthMonthComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 70, -1));

        birthDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        birthDateComboBox.setEnabled(false);
        detailsJPanel.add(birthDateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, -1));

        birthYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", " " }));
        birthYearComboBox.setEnabled(false);
        detailsJPanel.add(birthYearComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, -1));

        jLabel4.setText("Unique Id:");
        detailsJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Passport", "Driving License", "State Id" }));
        idComboBox.setEnabled(false);
        detailsJPanel.add(idComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 260, 30));

        jLabel5.setText("Date of Birth:");
        detailsJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        middleNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        middleNameJtext.setText("Middle name:");
        middleNameJtext.setEnabled(false);
        middleNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                middleNameJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(middleNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 140, 30));
        detailsJPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 178, 870, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Personal Information:");
        detailsJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 30));

        firstNameJtext.setForeground(new java.awt.Color(204, 204, 204));
        firstNameJtext.setText("First Name:");
        firstNameJtext.setEnabled(false);
        firstNameJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(firstNameJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, 30));

        jLabel6.setText("Name:");
        detailsJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        primaryPhoneNoJtext.setForeground(new java.awt.Color(204, 204, 204));
        primaryPhoneNoJtext.setText("Primary Contact no:");
        primaryPhoneNoJtext.setEnabled(false);
        primaryPhoneNoJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                primaryPhoneNoJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                primaryPhoneNoJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(primaryPhoneNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 250, 30));

        jLabel7.setText("Address:");
        detailsJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        idNoJtext.setForeground(new java.awt.Color(204, 204, 204));
        idNoJtext.setText("Id no:");
        idNoJtext.setEnabled(false);
        idNoJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idNoJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idNoJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(idNoJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 160, 30));

        cityJtext.setForeground(new java.awt.Color(204, 204, 204));
        cityJtext.setText("City");
        cityJtext.setEnabled(false);
        cityJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(cityJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 140, 30));

        stateJtext.setForeground(new java.awt.Color(204, 204, 204));
        stateJtext.setText("State");
        stateJtext.setEnabled(false);
        stateJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(stateJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 140, 30));

        jLabel10.setText("Contact no:");
        detailsJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Contact Information:");
        detailsJPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        streetJtext.setForeground(new java.awt.Color(204, 204, 204));
        streetJtext.setText("Street");
        streetJtext.setEnabled(false);
        streetJtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetJtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetJtextFocusLost(evt);
            }
        });
        detailsJPanel.add(streetJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 250, 30));

        firstNameValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        firstNameValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        firstNameValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(firstNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        middleNameValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        middleNameValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        middleNameValidatorJlbl.setText("jLabel16");
        detailsJPanel.add(middleNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 170, -1));

        lastNameValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lastNameValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        lastNameValidatorJlbl.setText("jLabel17");
        detailsJPanel.add(lastNameValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 180, -1));

        dateValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dateValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        dateValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(dateValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 160, -1));

        secondaryContactNoValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        secondaryContactNoValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        secondaryContactNoValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(secondaryContactNoValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 250, -1));

        addressValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        addressValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(addressValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, -1));

        yearValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yearValidatorJlbl.setForeground(new java.awt.Color(255, 0, 0));
        yearValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(yearValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, -1));

        monthValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthValidatorJlbl.setForeground(new java.awt.Color(255, 51, 51));
        monthValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(monthValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));

        primaryContactNoValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        primaryContactNoValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        primaryContactNoValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(primaryContactNoValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 250, -1));

        stateValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stateValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        stateValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(stateValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 160, -1));

        idNoValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idNoValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        idNoValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(idNoValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 160, -1));

        zipCodeValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        zipCodeValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        zipCodeValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(zipCodeValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 150, -1));

        cityValidatorJlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cityValidatorJlbl.setForeground(new java.awt.Color(255, 0, 51));
        cityValidatorJlbl.setText("jLabel15");
        detailsJPanel.add(cityValidatorJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 150, -1));

        add(detailsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 900, 340));

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJtextFocusGained

    private void emailIdJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIdJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdJtextFocusGained

    private void secondaryPhoneNoJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondaryPhoneNoJtextFocusGained
        // TODO add your handling code here:
        secondaryPhoneNoJtext.setText("");
        secondaryPhoneNoJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_secondaryPhoneNoJtextFocusGained

    private void firstNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJtextFocusGained
        // TODO add your handling code here:
        firstNameJtext.setText("");
        firstNameJtext.setForeground(Color.black);
        
        
    }//GEN-LAST:event_firstNameJtextFocusGained

    private void primaryPhoneNoJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_primaryPhoneNoJtextFocusGained
        // TODO add your handling code here:
        
        
            primaryPhoneNoJtext.setText("");
            primaryPhoneNoJtext.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_primaryPhoneNoJtextFocusGained

    private void streetJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetJtextFocusGained
        // TODO add your handling code here:
        
            streetJtext.setText("");
            streetJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_streetJtextFocusGained

    private void roleJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roleJtextFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_roleJtextFocusGained

    private void saveAccountJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAccountJbuttonActionPerformed
        // TODO add your handling code here:
        
        if(!validateAccountForm())
        {
            userAccount.setPassword(String.valueOf(passwordJtext.getPassword()));
            JOptionPane.showMessageDialog(null,"Password updated successfully");
        }
    }//GEN-LAST:event_saveAccountJbuttonActionPerformed

    private void passwordJtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordJtextKeyPressed
        passwordStrengthJlbl.setText("Password Strength:");
        passwordValidatorJlbl.setText("");
        String pattern = "(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{5,10}";
       boolean flag = String.valueOf(passwordJtext.getPassword()).trim().matches(pattern);
       if(flag)
       {
        passwordStrengthValueJlbl.setText("Good");
        passwordStrengthValueJlbl.setForeground(Color.green);
       }
       
       else
       {
       passwordStrengthValueJlbl.setText("Bad");
        passwordStrengthValueJlbl.setForeground(Color.red);    
       }
           
               // TODO add your handling code here:
    }//GEN-LAST:event_passwordJtextKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        detailsJPanel.setEnabled(true);
        detailsJPanel.setBackground(Color.WHITE);
        firstNameJtext.setEnabled(true);
        middleNameJtext.setEnabled(true);
        lastNameJtext.setEnabled(true);
        idNoJtext.setEnabled(true);primaryPhoneNoJtext.setEnabled(true);secondaryPhoneNoJtext.setEnabled(true);streetJtext.setEnabled(true);
        cityJtext.setEnabled(true);stateJtext.setEnabled(true);zipcodeJtext.setEnabled(true);
        birthMonthComboBox.setEnabled(true);
        birthYearComboBox.setEnabled(true);
        birthDateComboBox.setEnabled(true);
        idComboBox.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hideAllLabels();
       if(!validateProfileDetails())
       {
           userAccount.getPerson().setFirstName(firstNameJtext.getText().trim());
           userAccount.getPerson().setLastName(lastNameJtext.getText().trim());
           if(!middleNameJtext.getText().trim().equalsIgnoreCase("Middle name:"))
           {
               userAccount.getPerson().setMiddleName(middleNameJtext.getText().trim());
           }
           
         Calendar c = new GregorianCalendar();
         c.set(Integer.parseInt(String.valueOf(birthYearComboBox.getSelectedItem())),
                 Integer.parseInt(String.valueOf(birthMonthComboBox.getSelectedItem())),
                 Integer.parseInt(String.valueOf(birthDateComboBox.getSelectedItem())));
         
           userAccount.getPerson().setDateOfBirth(new Date(c.getTimeInMillis()));
           userAccount.getPerson().setIdType(String.valueOf(idComboBox.getSelectedItem()));
           userAccount.getPerson().setUniqueId(idNoJtext.getText().trim());
           userAccount.getPerson().setPrimaryContactNo(primaryPhoneNoJtext.getText().trim());
           userAccount.getPerson().setSecondaryContactNo(secondaryPhoneNoJtext.getText().trim());
           userAccount.getPerson().getAddress().setStreetName(streetJtext.getText().trim());
           userAccount.getPerson().getAddress().setCityName(cityJtext.getText().trim());
           userAccount.getPerson().getAddress().setStateName(stateJtext.getText().trim());
           
           JOptionPane.showMessageDialog(null,"All the details are successfully updated","Data updated",JOptionPane.INFORMATION_MESSAGE);
           return;
           
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void middleNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameJtextFocusGained
            // TODO add your handling code here:
        middleNameJtext.setText("");
        middleNameJtext.setForeground(Color.black);
    }//GEN-LAST:event_middleNameJtextFocusGained

    private void firstNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameJtextFocusLost
        // TODO add your handling code here:
        
        if(firstNameJtext.getText().trim().equals(""))
        {
            firstNameJtext.setText("First name:");
            firstNameJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_firstNameJtextFocusLost

    private void middleNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameJtextFocusLost
        // TODO add your handling code here:
        
        if(middleNameJtext.getText().trim().equals(""))
        {
            middleNameJtext.setText("First name:");
            middleNameJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_middleNameJtextFocusLost

    private void lastNameJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJtextFocusGained
        // TODO add your handling code here:
        
            lastNameJtext.setText("");
            lastNameJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_lastNameJtextFocusGained

    private void lastNameJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameJtextFocusLost
        // TODO add your handling code here:
        
        if(lastNameJtext.getText().trim().equals(""))
        {
            lastNameJtext.setText("");
            lastNameJtext.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_lastNameJtextFocusLost

    private void idNoJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNoJtextFocusGained
        // TODO add your handling code here:
        
        idNoJtext.setText("");
            idNoJtext.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_idNoJtextFocusGained

    private void idNoJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idNoJtextFocusLost
        // TODO add your handling code here:
        
        if(idNoJtext.getText().trim().equals(""))
        {
            idNoJtext.setText("Id no:");
            idNoJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_idNoJtextFocusLost

    private void primaryPhoneNoJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_primaryPhoneNoJtextFocusLost
        // TODO add your handling code here:
        
        if(primaryPhoneNoJtext.getText().trim().equals(""))
        {
           primaryPhoneNoJtext.setText("Primary Contact no:");
            primaryPhoneNoJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_primaryPhoneNoJtextFocusLost

    private void secondaryPhoneNoJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_secondaryPhoneNoJtextFocusLost
        // TODO add your handling code here:
        if(secondaryPhoneNoJtext.getText().trim().equals(""))
        {
        secondaryPhoneNoJtext.setText("Secondary Contact no:");
        secondaryPhoneNoJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_secondaryPhoneNoJtextFocusLost

    private void streetJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetJtextFocusLost
        // TODO add your handling code here:
        
        if(streetJtext.getText().trim().equals(""))
        {
            streetJtext.setText("");
            streetJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_streetJtextFocusLost

    private void cityJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJtextFocusGained
        // TODO add your handling code here:
        
        cityJtext.setText("");
            cityJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_cityJtextFocusGained

    private void cityJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJtextFocusLost
        // TODO add your handling code here:
        
        if(cityJtext.getText().trim().equals(""))
        {
            cityJtext.setText("City");
            cityJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_cityJtextFocusLost

    private void stateJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJtextFocusGained
        // TODO add your handling code here:
        
        stateJtext.setText("");
            stateJtext.setForeground(Color.BLACK);
    }//GEN-LAST:event_stateJtextFocusGained

    private void stateJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJtextFocusLost
        // TODO add your handling code here:
        if(stateJtext.getText().trim().equals(""))
        {
            stateJtext.setText("State");
            stateJtext.setForeground(Color.LIGHT_GRAY);
        }
        
    }//GEN-LAST:event_stateJtextFocusLost

    private void zipcodeJtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipcodeJtextFocusGained
        // TODO add your handling code here:
        zipcodeJtext.setText("");
            zipcodeJtext.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_zipcodeJtextFocusGained

    private void zipcodeJtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipcodeJtextFocusLost
        // TODO add your handling code here:
        
        if(zipcodeJtext.getText().trim().equals(""))
        {
            zipcodeJtext.setText("Zipcode");
            zipcodeJtext.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_zipcodeJtextFocusLost

    
    public boolean validateProfileDetails()
    {
        boolean errorFlag=false;
        
        if(!Validation.validateTextFieldsForNonEmpty(firstNameJtext)||firstNameJtext.getText().trim().equalsIgnoreCase("First name"))
        {
        errorFlag=true;
        firstNameValidatorJlbl.setText("Please enter first name");
            
        }
        
        else if(!Validation.validateTextFieldsForString(firstNameJtext))
        {
            errorFlag=true;
            firstNameValidatorJlbl.setText("Enter valid name");
        }
        
        
        if(!Validation.validateTextFieldsForNonEmpty(lastNameJtext)||lastNameJtext.getText().trim().equalsIgnoreCase("Last name"))
        {
        errorFlag=true;
        lastNameValidatorJlbl.setText("Please enter last name");
            
        }
        
        else if(!Validation.validateTextFieldsForString(lastNameJtext))
        {
            errorFlag=true;
            lastNameValidatorJlbl.setText("Enter valid name");
        }
        
        if(!Validation.validateTextFieldsForString(middleNameJtext))
        {
            errorFlag=true;
            middleNameValidatorJlbl.setText("Enter valid name");
        }
        
        
        if(String.valueOf(birthMonthComboBox.getSelectedItem()).equalsIgnoreCase("MM"))
        {
            errorFlag=true;
            monthValidatorJlbl.setText("Please select month");
        }
        
        if(String.valueOf(birthDateComboBox.getSelectedItem()).equalsIgnoreCase("DD"))
        {
            errorFlag=true;
            dateValidatorJlbl.setText("Please select date");
        }
        
        
        if(String.valueOf(birthYearComboBox.getSelectedItem()).equalsIgnoreCase("YYYY"))
        {
            errorFlag=true;
            yearValidatorJlbl.setText("Please select year");
        }
        
        
        if(!Validation.validateTextFieldsForString(idNoJtext)||idNoJtext.getText().trim().equalsIgnoreCase("Id no:"))
        {
            errorFlag=true;
            idNoValidatorJlbl.setText("Enter valid id no:");
        }
        
        if(!Validation.validateTextFieldsForPhoneNumber(primaryPhoneNoJtext))
        {
            errorFlag=true;
            primaryContactNoValidatorJlbl.setText("Enter valid primary contact no.");
        }
        
        
        if(!Validation.validateTextFieldsForPhoneNumber(secondaryPhoneNoJtext))
        {
            errorFlag=true;
            secondaryContactNoValidatorJlbl.setText("Enter valid secondary contact no.");
        }
        
        
        if(!Validation.validateTextFieldsForString(streetJtext)||streetJtext.getText().trim().equalsIgnoreCase("Street"))
        {
            errorFlag=true;
            addressValidatorJlbl.setText("Please enter valid street");
        }
        
        
        if(!Validation.validateTextFieldsForString(cityJtext)||cityJtext.getText().trim().equalsIgnoreCase("City"))
        {
            errorFlag=true;
            cityValidatorJlbl.setText("Please enter valid city");
        }
        
        if(!Validation.validateTextFieldsForString(stateJtext)||stateJtext.getText().trim().equalsIgnoreCase("State"))
        {
            errorFlag=true;
            stateValidatorJlbl.setText("Please enter valid state");
        }
        
        if(!Validation.validateTextFieldsForInteger(zipcodeJtext)||zipcodeJtext.getText().trim().equalsIgnoreCase("Zip code"))
        {
            errorFlag=true;
            zipCodeValidatorJlbl.setText("Please enter valid zipcode");
        }
        
        
        return errorFlag;
        
        
    }
    public boolean validateAccountForm()
    {
        boolean errorFlag=false;
        
        if(!Validation.validateTextFieldForPassword(passwordJtext)||passwordJtext.getPassword().equals(""))
        {
            errorFlag=true;
            passwordValidatorJlbl.setText("Please enter valid password");
            passwordValidatorJlbl.setVisible(true);
        }
        
        return errorFlag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressValidatorJlbl;
    private javax.swing.JComboBox birthDateComboBox;
    private javax.swing.JComboBox birthMonthComboBox;
    private javax.swing.JComboBox birthYearComboBox;
    private javax.swing.JTextField cityJtext;
    private javax.swing.JLabel cityValidatorJlbl;
    private javax.swing.JLabel dateValidatorJlbl;
    private javax.swing.JLayeredPane detailsJPanel;
    private javax.swing.JTextField emailIdJtext;
    private javax.swing.JTextField firstNameJtext;
    private javax.swing.JLabel firstNameValidatorJlbl;
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JTextField idNoJtext;
    private javax.swing.JLabel idNoValidatorJlbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastNameJtext;
    private javax.swing.JLabel lastNameValidatorJlbl;
    private javax.swing.JTextField middleNameJtext;
    private javax.swing.JLabel middleNameValidatorJlbl;
    private javax.swing.JLabel monthValidatorJlbl;
    private javax.swing.JPasswordField passwordJtext;
    private javax.swing.JLabel passwordStrengthJlbl;
    private javax.swing.JLabel passwordStrengthValueJlbl;
    private javax.swing.JLabel passwordValidatorJlbl;
    private javax.swing.JLabel primaryContactNoValidatorJlbl;
    private javax.swing.JTextField primaryPhoneNoJtext;
    private javax.swing.JLayeredPane profileDetailsJPanel;
    private javax.swing.JTextField roleJtext;
    private javax.swing.JButton saveAccountJbutton;
    private javax.swing.JLabel secondaryContactNoValidatorJlbl;
    private javax.swing.JTextField secondaryPhoneNoJtext;
    private javax.swing.JTextField stateJtext;
    private javax.swing.JLabel stateValidatorJlbl;
    private javax.swing.JTextField streetJtext;
    private javax.swing.JTextField userNameJtext;
    private javax.swing.JLabel welcomeJlbl;
    private javax.swing.JLabel yearValidatorJlbl;
    private javax.swing.JLabel zipCodeValidatorJlbl;
    private javax.swing.JTextField zipcodeJtext;
    // End of variables declaration//GEN-END:variables
}
