/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.AccountsManager;

import Business.Bank.BankEnterprise;
import Business.Enterprise.DonationEnterprise;
import Business.Enterprise.Enterprise;
import Business.Payment.Payment;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JJPL
 */
public class AccountManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagerWorkAreaJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DonationEnterprise donationEnterprise;
    private BankEnterprise bankEnterprise;
    
    public AccountManagerWorkAreaJPanel(JPanel upc,Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        if(enterprise instanceof DonationEnterprise)
        donationEnterprise = (DonationEnterprise)enterprise;
        enterpriseJlbl.setText(donationEnterprise.getName());
        welcomeJlbl.setText("Welcome"+userAccount.getUsername());
        populateAccountSummary();
        transferMoneyJPanel.setVisible(false);
    }
    
    public void populateAccountSummary()
    {
        accountNoJtext1.setText(String.valueOf(donationEnterprise.getLocalEnterpriseBankAccount().getAccountNumber()));
        for (Enterprise e:donationEnterprise.getAssociatedEnterprise())
        {
            if(e instanceof BankEnterprise)
                bankEnterprise = (BankEnterprise)e;
        }
        bankNameJtext.setText(bankEnterprise.getBankName());
        availableBalanceJtext.setText(String.valueOf(donationEnterprise.getLocalEnterpriseBankAccount().getAccountBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseJlbl = new javax.swing.JLabel();
        accountSummaryJPanel = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        viewStatementJbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        availableBalanceJtext = new javax.swing.JTextField();
        accountNoJtext1 = new javax.swing.JTextField();
        bankNameJtext = new javax.swing.JTextField();
        welcomeJlbl = new javax.swing.JLabel();
        transferMoneyJbutton = new javax.swing.JButton();
        transferMoneyJPanel = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donationRequestsJtable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseJlbl.setText("-");
        add(enterpriseJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 11, 190, -1));

        accountSummaryJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ACCOUNT WITH BANK:");
        accountSummaryJPanel.add(jLabel2);
        jLabel2.setBounds(90, 90, 230, 20);
        accountSummaryJPanel.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 940, 10);

        jLabel3.setText("ACCOUNT NO:");
        accountSummaryJPanel.add(jLabel3);
        jLabel3.setBounds(90, 60, 80, 20);

        viewStatementJbutton.setText("VIEW");
        accountSummaryJPanel.add(viewStatementJbutton);
        viewStatementJbutton.setBounds(340, 180, 100, 23);

        jLabel6.setText("AVAILABLE BALANCE:");
        accountSummaryJPanel.add(jLabel6);
        jLabel6.setBounds(90, 140, 200, 20);

        jLabel7.setText("MINI STATEMENT:");
        accountSummaryJPanel.add(jLabel7);
        jLabel7.setBounds(90, 180, 110, 20);

        jLabel8.setText("ACCOUNT SUMMARY:");
        accountSummaryJPanel.add(jLabel8);
        jLabel8.setBounds(10, 10, 110, 20);

        availableBalanceJtext.setEnabled(false);
        accountSummaryJPanel.add(availableBalanceJtext);
        availableBalanceJtext.setBounds(340, 140, 120, 30);

        accountNoJtext1.setEnabled(false);
        accountSummaryJPanel.add(accountNoJtext1);
        accountNoJtext1.setBounds(340, 50, 320, 30);

        bankNameJtext.setEnabled(false);
        accountSummaryJPanel.add(bankNameJtext);
        bankNameJtext.setBounds(340, 90, 250, 30);

        add(accountSummaryJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 940, 210));
        add(welcomeJlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 140, 20));

        transferMoneyJbutton.setText("Donations to be transferred");
        transferMoneyJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMoneyJbuttonActionPerformed(evt);
            }
        });
        add(transferMoneyJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 240, 30));

        transferMoneyJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("SELECT COUNTRY:");
        transferMoneyJPanel.add(jLabel5);
        jLabel5.setBounds(180, -30, 330, 20);

        donationRequestsJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Amount", "Region", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(donationRequestsJtable);

        transferMoneyJPanel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 900, 100);
        transferMoneyJPanel.add(jSeparator2);
        jSeparator2.setBounds(0, 32, 950, 10);

        jLabel4.setText("NEW DONATIONS:");
        transferMoneyJPanel.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 20);

        add(transferMoneyJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 351, 950, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void transferMoneyJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMoneyJbuttonActionPerformed
        // TODO add your handling code here:
        transferMoneyJPanel.setVisible(true);
        populateDonationRequests();
    }//GEN-LAST:event_transferMoneyJbuttonActionPerformed

    public void populateDonationRequests()
    {
        Payment payment;
        DefaultTableModel dtm = (DefaultTableModel)donationRequestsJtable.getModel();
        dtm.setRowCount(0);
        
        for(WorkQueue workQueue:donationEnterprise.getWorkQueueList())
        {
        
        for (WorkRequest workRequest:workQueue.getWorkRequestList())
        {
            if (workRequest instanceof Payment)
            {   
                payment = (Payment)workRequest;
                Object row[]=new Object[4];
                row[0]=payment.getRequestId();
                row[1]=payment.getAmount();
                row[2]=payment.getRegion();
                row[3]=payment.getRequestDate();
                dtm.addRow(row);
            }
        }
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoJtext1;
    private javax.swing.JLayeredPane accountSummaryJPanel;
    private javax.swing.JTextField availableBalanceJtext;
    private javax.swing.JTextField bankNameJtext;
    private javax.swing.JTable donationRequestsJtable;
    private javax.swing.JLabel enterpriseJlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLayeredPane transferMoneyJPanel;
    private javax.swing.JButton transferMoneyJbutton;
    private javax.swing.JButton viewStatementJbutton;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
